In [1]:
# Numpy 的資料型態

import numpy as np
dt = np.dtype([('name', 'U10'),
               ('age', 'i4'),
               ('score', 'f4')])
data = np.array([("Alice", 25, 88.5),
                 ("Bob", 30, 92.0)],
                 dtype=dt)
print(data)

[('Alice', 25, 88.5) ('Bob', 30, 92. )]


In [2]:
# Numpy 的資料型態
# 使用array 函式建立㇐維陣列
import numpy as np
x = np.array([1, 2, 3])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[1 2 3]


In [3]:
# Numpy 的資料型態
# 列出陣列元素內容
import numpy as np
x = np.array([1, 2, 3])
print(x[0])
print(x[1])
print(x[2])

1
2
3


In [4]:
# Numpy 的資料型態
# 設定陣列內容
import numpy as np
x = np.array([1, 2, 3])
x[1] = 10
print(x)

[ 1 10  3]


In [5]:
# Numpy 的資料型態
# 認識ndarray 陣列的屬性
import numpy as np
x = np.array([1, 2, 3])
print(x.dtype)
print(x.itemsize)
print(x.ndim)
print(x.shape)
print(x.size)

int64
8
1
(3,)
3


In [6]:
# Numpy 的資料型態
# 設定ndarray 陣列的元素資料型態
import numpy as np
x = np.array([1, 2, 3], dtype=np.int8)
print(x.dtype)
print(x.itemsize)
print(x.ndim)
print(x.shape)
print(x.size)

int8
1
1
(3,)
3


In [7]:
# Numpy 的資料型態
# 浮點數陣列的建立與列印
import numpy as np
x = np.array([1.1, 2.3, 3.6])
print(x.dtype)
print(x.itemsize)
print(x.ndim)
print(x.shape)
print(x.size)
print(x)

float64
8
1
(3,)
3
[1.1 2.3 3.6]


In [8]:
# Numpy 的資料型態
# 使用array 函式建立多維陣列
import numpy as np
row1 = [1, 2, 3]
arr1 = np.array(row1, ndmin=2)
print(f"陣列維度 = {arr1.ndim}")
print(f"陣列外型 = {arr1.shape}")
print(f"陣列大小 = {arr1.size}")
print("陣列內容")
print(arr1)
print("-"*70)
row2 = [4, 5, 6]
arr2 = np.array([row1, row2], ndmin=2)
print(f"陣列維度 = {arr2.ndim}")
print(f"陣列外型 = {arr2.shape}")
print(f"陣列大小 = {arr2.size}")
print("陣列內容")
print(arr2)

陣列維度 = 2
陣列外型 = (1, 3)
陣列大小 = 3
陣列內容
[[1 2 3]]
----------------------------------------------------------------------
陣列維度 = 2
陣列外型 = (2, 3)
陣列大小 = 6
陣列內容
[[1 2 3]
 [4 5 6]]


In [9]:
# Numpy 的資料型態
# 使用array 函式建立多維陣列
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(f"陣列維度 = {x.ndim}")
print(f"陣列外型 = {x.shape}")
print(f"陣列大小 = {x.size}")
print("陣列內容")
print(x)

陣列維度 = 2
陣列外型 = (2, 3)
陣列大小 = 6
陣列內容
[[1 2 3]
 [4 5 6]]


In [10]:
# Numpy 的資料型態
# 二維陣列的索引
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x[0][2])
print(x[1][2])
 # 或是
print(x[0, 2])
print(x[1, 2])

3
6
3
6


In [11]:
# Numpy 的資料型態
# 使用zeros 函式建立內容都是0的陣列
import numpy as np
x1 = np.zeros(3)
print(x1)
print("-"*70)
x2 = np.zeros((2, 3), dtype=np.uint8)
print(x2)

[0. 0. 0.]
----------------------------------------------------------------------
[[0 0 0]
 [0 0 0]]


In [12]:
# Numpy 的資料型態
# 內容都是0的陣列相當於㇐張黑色影像
import cv2
import numpy as np
fig = np.zeros((50, 200), dtype=np.uint8)
print(fig)
cv2.imshow("fig", fig)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
# Numpy 的資料型態
# 使用ones 函式建立內容都是1的陣列
import numpy as np
x1 = np.ones(3)
print(x1)
print("-"*70)
x2 = np.ones((2, 3), dtype=np.uint8)
print(x2)

[1. 1. 1.]
----------------------------------------------------------------------
[[1 1 1]
 [1 1 1]]


In [14]:
# Numpy 的資料型態
# 內容都是255的陣列相當於㇐張白色影像
import cv2
import numpy as np
fig = np.ones((50, 200), dtype=np.uint8) * 255
print(fig)
cv2.imshow("fig", fig)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [15]:
# Numpy 的資料型態
# 使用empty 函式建立未初始化的陣列
import numpy as np
x1 = np.empty(3)
print(x1)
print("-"*70)
x2 = np.empty((2, 3), dtype=np.uint8)
print(x2)

[1. 1. 1.]
----------------------------------------------------------------------
[[0 0 0]
 [0 0 0]]


In [16]:
# Numpy 的資料型態
# 使用random.randint 函式建立隨機內容的陣列
import numpy as np
x1 = np.random.randint(10, 20)
print("回傳值是10(含)至20(不含)的單一隨機數")
print(x1)
print("-"*70)
print("回傳一維陣列10個元素, 值是1(含)至5(不含)的隨機數")
x2 = np.random.randint(1, 5, 10)
print(x2)
print("-"*70)
print("回傳單3*5陣列, 值是0(含)至10(不含)的隨機數")
x3 = np.random.randint(10, size=(3, 5))
print(x3)

回傳值是10(含)至20(不含)的單一隨機數
11
----------------------------------------------------------------------
回傳一維陣列10個元素, 值是1(含)至5(不含)的隨機數
[3 1 4 2 3 3 2 4 2 1]
----------------------------------------------------------------------
回傳單3*5陣列, 值是0(含)至10(不含)的隨機數
[[1 3 7 2 0]
 [9 5 3 6 6]
 [4 3 4 5 1]]


In [17]:
# Numpy 的資料型態
# 使用arange 函式建立陣列資料
import numpy as np
x = np.arange(16)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [18]:
# Numpy 的資料型態
# 使用reshape 函式變更陣列的形狀
import numpy as np
x = np.arange(16)
print(x)
print(np.reshape(x, (2, 8)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [19]:
# Numpy 的資料型態
# 使用reshape 函式變更陣列的形狀
import numpy as np
x = np.arange(16)
print(x)
print(np.reshape(x, (4, -1)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
# Numpy 的資料型態
# 使用reshape 函式變更陣列的形狀
import numpy as np
x = np.arange(16)
print(x)
print(np.reshape(x, (-1, 8)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [21]:
# Numpy 的資料型態
# 陣列的四則運算
import numpy as np
x = np.array([1, 2, 3])
y = x + 5
print(y)

[6 7 8]


In [22]:
# Numpy 的資料型態
# 陣列的四則運算
import numpy as np
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = x + y
print(z)

[11 22 33]


In [23]:
# Numpy 的資料型態
# 陣列的四則運算
import numpy as np
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = x * y
print(z)

[10 40 90]


In [24]:
# Numpy 的資料型態
# 陣列的四則運算
import numpy as np
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = x / y
print(z)
z = y / x
print(z)

[0.1 0.1 0.1]
[10. 10. 10.]


In [25]:
# Numpy 的資料型態
# 陣列的關係運算
import numpy as np
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = x > y
print(z)
z = x < y
print(z)

[False False False]
[ True  True  True]


In [26]:
# Numpy 的資料型態
# 陣列的切片
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"陣列元素如下 : {x} ")
print(f"x[2:]       = {x[2:]}")
print(f"x[:2]       = {x[:3]}")
print(f"x[0:3]      = {x[0:3]}")
print(f"x[1:4]      = {x[1:4]}")
print(f"x[0:9:2]    = {x[0:9:2]}")
print(f"x[-1]       = {x[-1]}")
print(f"x[::2]      = {x[::2]}")
print(f"x[2::3]     = {x[2::3]}")
print(f"x[:]        = {x[:]}")
print(f"x[::]       = {x[::]}")
print(f"x[-3:-7:-1] = {x[-3:-7:-1]}")

陣列元素如下 : [0 1 2 3 4 5 6 7 8 9] 
x[2:]       = [2 3 4 5 6 7 8 9]
x[:2]       = [0 1 2]
x[0:3]      = [0 1 2]
x[1:4]      = [1 2 3]
x[0:9:2]    = [0 2 4 6 8]
x[-1]       = 9
x[::2]      = [0 2 4 6 8]
x[2::3]     = [2 5 8]
x[:]        = [0 1 2 3 4 5 6 7 8 9]
x[::]       = [0 1 2 3 4 5 6 7 8 9]
x[-3:-7:-1] = [7 6 5 4]


In [27]:
# Numpy 的資料型態
# Numpy array 函式的copy 參數
import numpy as np
x1 = np.array([0, 1, 2, 3, 4, 5])
x2 = np.array(x1, copy=True)
x3 = np.array(x1, copy=False)
print(x1)
print(x2)
print(x3)
print('-'*70)
x2[0] = 7
x3[0] = 8
print(x1)
print(x2)
print(x3)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
----------------------------------------------------------------------
[8 1 2 3 4 5]
[7 1 2 3 4 5]
[8 1 2 3 4 5]


In [28]:
# Numpy 的資料型態
# Numpy ndarray 類別的 copy 方法
import numpy as np
x1 = np.array([0, 1, 2, 3, 4, 5])
x2 = x1.copy()
x3 = x1
print(x1)
print(x2)
print(x3)
print('-'*70)
x2[0] = 7
x3[0] = 8
print(x1)
print(x2)
print(x3)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
----------------------------------------------------------------------
[8 1 2 3 4 5]
[7 1 2 3 4 5]
[8 1 2 3 4 5]


In [29]:
# Numpy 的資料型態
# 多維陣列的索引
import numpy as np
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x3 = [10, 11, 12, 13, 14]
x4 = np.array([x1, x2, x3])
print(x4)
print(f"x4[2][1] = {x4[2][1]}")
print(f"x4[1][3] = {x4[1][3]}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
x4[2][1] = 11
x4[1][3] = 8


In [31]:
# Numpy 的資料型態
# 多維陣列的索引
import numpy as np
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x3 = [10, 11, 12, 13, 14]
x4 = np.array([x1, x2, x3])
print(x4)
print(f"x4[2, 1] = {x4[2, 1]}")
print(f"x4[1, 3] = {x4[1, 3]}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
x4[2, 1] = 11
x4[1, 3] = 8


In [30]:
# Numpy 的資料型態
# 多維陣列的索引
import numpy as np
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x3 = [10, 11, 12, 13, 14]
x4 = np.array([x1, x2, x3])
x5 = np.array([x4, x4])
print(x5)
print(f"x5[0][2][1] = {x5[0][2][1]}")
print(f"x5[0][1][3] = {x5[0][1][3]}")
print(f"x5[1][0][1] = {x5[1][0][1]}")
print(f"x5[1][1][4] = {x5[1][1][4]}")

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
x5[0][2][1] = 11
x5[0][1][3] = 8
x5[1][0][1] = 1
x5[1][1][4] = 9


In [32]:
# Numpy 的資料型態
# 多維陣列的索引
import numpy as np
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x3 = [10, 11, 12, 13, 14]
x4 = np.array([x1, x2, x3])
x5 = np.array([x4, x4])
print(x5)
print(f"x5[0, 2, 1] = {x5[0, 2, 1]}")
print(f"x5[0, 1, 3] = {x5[0, 1, 3]}")
print(f"x5[1, 0, 1] = {x5[1, 0, 1]}")
print(f"x5[1, 1, 4] = {x5[1, 1, 4]}")

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
x5[0, 2, 1] = 11
x5[0, 1, 3] = 8
x5[1, 0, 1] = 1
x5[1, 1, 4] = 9


In [33]:
# Numpy 的資料型態
# 多維陣列的切片
import numpy as np
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x3 = [10, 11, 12, 13, 14]
x = np.array([x1, x2, x3])
print(x)
print("x[:, :] = 結果是二維陣列")
print(x[:, :])
print("-"*70)
print("x[2, :4] = 結果是一維陣列")
print(x[2, :4])
print("-"*70)
print("x[:2, :1] = 結果是二維陣列")
print(x[:2, :1])
print("-"*70)
print("x[:, 4:] = 結果是二維陣列")
print(x[:, 4:])
print("-"*70)
print("x[:, 4] = 結果是一維陣列")
print(x[:, 4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
x[:, :] = 結果是二維陣列
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
----------------------------------------------------------------------
x[2, :4] = 結果是一維陣列
[10 11 12 13]
----------------------------------------------------------------------
x[:2, :1] = 結果是二維陣列
[[0]
 [5]]
----------------------------------------------------------------------
x[:, 4:] = 結果是二維陣列
[[ 4]
 [ 9]
 [14]]
----------------------------------------------------------------------
x[:, 4] = 結果是一維陣列
[ 4  9 14]


In [42]:
# Numpy 的資料型態
# 多維陣列的切片
import numpy as np
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x3 = [10, 11, 12, 13, 14]
x = np.array([x1, x2, x3])
print(f'x = {x}')
print("x[:2, 4] = 結果是一維陣列")
print(x[:2, 4])
print("-"*70)
print("x[:2][4] = 結果是?")
print(x[:2][4])

x = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
x[:2, 4] = 結果是一維陣列
[4 9]
----------------------------------------------------------------------
x[:2][4] = 結果是?


IndexError: index 4 is out of bounds for axis 0 with size 2

In [43]:
# Numpy 的資料型態
# 陣列垂直合併
import numpy as np
x1 = np.arange(4).reshape(2, 2)
print(f"陣列 1 \n{x1}")
x2 = np.arange(4, 8).reshape(2, 2)
print(f"陣列 2 \n{x2}")
x = np.vstack((x1, x2))
print(f"合併結果 \n{x}")

陣列 1 
[[0 1]
 [2 3]]
陣列 2 
[[4 5]
 [6 7]]
合併結果 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [44]:
# Numpy 的資料型態
# 陣列水平合併
import numpy as np
x1 = np.arange(4).reshape(2, 2)
print(f"陣列 1 \n{x1}")
x2 = np.arange(4, 8).reshape(2, 2)
print(f"陣列 2 \n{x2}")
x = np.hstack((x1, x2))
print(f"合併結果 \n{x}")

陣列 1 
[[0 1]
 [2 3]]
陣列 2 
[[4 5]
 [6 7]]
合併結果 
[[0 1 4 5]
 [2 3 6 7]]


In [45]:
# Numpy 的資料型態
# 建立灰階影像
import cv2
import numpy as np
height = 160
width = 280
image = np.zeros((height, width), np.uint8)
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
# Numpy 的資料型態
# 建立灰階影像
import cv2
import numpy as np
height = 160
width = 280
image = np.zeros((height, width), np.uint8)
image.fill(255)
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [47]:
# Numpy 的資料型態
# 建立灰階影像
import cv2
import numpy as np
height = 160
width = 280
image = np.ones((height, width), np.uint8)
image = image * 255
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
# Numpy 的資料型態
# 編輯灰階影像
import cv2
import numpy as np
height = 160
width = 280
image = np.zeros((height, width), np.uint8)
image[40:120, 70:210] = 255
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
# Numpy 的資料型態
# 編輯灰階影像
import cv2
import numpy as np
height = 160
width = 280
image = np.zeros((height, width), np.uint8)
for y in range(0, height, 20):
    image[y:y+10, :] = 255
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
# Numpy 的資料型態
# 建立彩色影像
import cv2
import numpy as np
height = 160
width = 280
image = np.zeros((height, width, 3), np.uint8)
image[:, :, 0] = 255
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [51]:
# Numpy 的資料型態
# 建立彩色影像
import cv2
import numpy as np
height = 160
width = 280
image = np.zeros((height, width, 3), np.uint8)
blue_image = image.copy()
blue_image[:, :, 0] = 255
cv2.imshow("blue image", blue_image)
green_image = image.copy()
green_image[:, :, 1] = 255
cv2.imshow("green image", green_image)
red_image = image.copy()
red_image[:, :, 2] = 255
cv2.imshow("red image", red_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
# Numpy 的資料型態
# 建立彩色影像
import cv2
import numpy as np
height = 150
width = 300
image = np.zeros((height, width, 3), np.uint8)
image[0:50, :, 0] = 255
image[50:100, :, 1] = 255
image[100:150, :, 2] = 255
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [53]:
# Numpy 的資料型態
# 建立彩色的隨機影像
import cv2
import numpy as np
height = 160
width = 280
image = np.random.randint(256, size=[height, width, 3], dtype=np.uint8)
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
