In [1]:
# 影像雜訊消除
# 產生高斯雜訊
import cv2
import numpy as np
img = cv2.imread("leclerc.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("src", img)
img_norm = img / 255.0                              # 正規化到 0~1
mean = 0
stddev = 0.1
gaussian_noise = np.random.normal(mean,
                                  stddev,
                                  img_norm.shape)   # 產生高斯雜訊
noisy_img = img_norm + gaussian_noise               # 把雜訊加入影像
noisy_img = np.clip(noisy_img, 0, 1)                # 裁切範圍
noisy_img_uint8 = (noisy_img * 255).astype(np.uint8)# 轉回 0~255 
cv2.imshow("Gaussian Noise", noisy_img_uint8)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('leclerc_gaussian_noise.png', noisy_img_uint8)

True

In [2]:
# 影像雜訊消除
# 產生椒鹽雜訊
import cv2
import numpy as np
img = cv2.imread("leclerc.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("src", img)
sp_img = img.copy()
prob = 0.02                         # 設定雜訊比例，2% 的像素受到影響
num_salt = np.ceil(prob * img.size * 0.5)
num_pepper = np.ceil(prob * img.size * 0.5)
coords = [np.random.randint(0, i, int(num_salt)) for i in img.shape]
sp_img[coords[0], coords[1]] = 255  # 加 salt 雜訊（白點）
coords = [np.random.randint(0, i, int(num_pepper)) for i in img.shape]
sp_img[coords[0], coords[1]] = 0    # 加 pepper 雜訊（黑點）
cv2.imshow("Salt-and-Pepper Noise", sp_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('leclerc_salt_pepper_noise.png', sp_img)

True

In [1]:
# 影像雜訊消除_濾波核(捲積核)
# blur() 均值濾波器
import cv2
src = cv2.imread("leclerc.png")
dst1 = cv2.blur(src, (3, 3)) 
dst2 = cv2.blur(src, (5, 5)) 
dst3 = cv2.blur(src, (7, 7)) 
cv2.imshow("src", src)
cv2.imshow("dst 3 x 3", dst1)
cv2.imshow("dst 5 x 5", dst2)
cv2.imshow("dst 7 x 7", dst3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 影像雜訊消除_濾波核(捲積核)
# boxFilter() 方框濾波器
import cv2
src = cv2.imread("leclerc_gaussian_noise.png")
 # src = cv2.imread("leclerc_salt_pepper_noise.png")
dst1 = cv2.boxFilter(src, -1, (3, 3), normalize=0)
dst2 = cv2.boxFilter(src, -1, (5, 5), normalize=0)
dst3 = cv2.boxFilter(src, -1, (7, 7), normalize=0)
cv2.imshow("src", src)
cv2.imshow("dst 3 x 3", dst1)
cv2.imshow("dst 5 x 5", dst2)
cv2.imshow("dst 7 x 7", dst3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# 影像雜訊消除_濾波核(捲積核)
# medianBlur() 中值濾波器
import cv2
import numpy as np
src = np.random.randint(0, 256, (3, 3), np.uint8)
src[1, 1] = 20
print(f"src = \n {src}")
dst = cv2.medianBlur(src, 3)
print(f"dst = \n {dst}")

src = 
 [[ 62 156 100]
 [ 55  20 181]
 [ 53  51 104]]
dst = 
 [[ 62 100 100]
 [ 55  62 104]
 [ 53  53 104]]


In [2]:
# 影像雜訊消除_濾波核(捲積核)
# medianBlur() 中值濾波器
import cv2
src = cv2.imread("leclerc_gaussian_noise.png")
# src = cv2.imread("leclerc_salt_pepper_noise.png")
dst1 = cv2.medianBlur(src, 3) # 使用邊長是 3 的濾波核
dst2 = cv2.medianBlur(src, 5) # 使用邊長是 5 的濾波核
dst3 = cv2.medianBlur(src, 7) # 使用邊長是 7 的濾波核
cv2.imshow("src", src)
cv2.imshow("dst 3 x 3", dst1)
cv2.imshow("dst 5 x 5", dst2)
cv2.imshow("dst 7 x 7", dst3)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [3]:
# 影像雜訊消除_濾波核(捲積核)
# GaussianBlur() 高斯濾波器
import cv2
src = cv2.imread("leclerc_gaussian_noise.png")
# src = cv2.imread("leclerc_salt_pepper_noise.png")
dst1 = cv2.GaussianBlur(src, (3, 3), 0, 0) 
dst2 = cv2.GaussianBlur(src, (5, 5), 0, 0) 
dst3 = cv2.GaussianBlur(src, (29, 29), 0, 0) 
cv2.imshow("src", src)
cv2.imshow("dst 3 x 3", dst1)
cv2.imshow("dst 5 x 5", dst2)
cv2.imshow("dst 29 x 29", dst3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 影像雜訊消除_濾波核(捲積核)
import cv2
src = cv2.imread("border.jpg")
dst1 = cv2.blur(src, (3, 3)) # 均值濾波器- 3x3 濾波核
dst2 = cv2.blur(src, (7, 7)) # 均值濾波器- 7x7 濾波核
dst3 = cv2.GaussianBlur(src, (3, 3), 0, 0) # 高斯濾波器- 3x3 的濾波核
dst4 = cv2.GaussianBlur(src, (7, 7), 0, 0) # 高斯濾波器- 7x7 的濾波核
cv2.imshow("src", src)
cv2.imshow("dst 3 x 3", dst1)
cv2.imshow("dst 7 x 7", dst2)
cv2.imshow("Gauss dst 3 x 3", dst3)
cv2.imshow("Gauss dst 7 x 7", dst4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# 影像雜訊消除_濾波核(捲積核)
# bilateralFilter() 雙邊濾波器
import cv2
src = cv2.imread("leclerc_gaussian_noise.png")
# src = cv2.imread("leclerc_salt_pepper_noise.png")
dst1 = cv2.blur(src, (15, 15)) 
dst2 = cv2.GaussianBlur(src, (15, 15), 0, 0) 
dst2 = cv2.bilateralFilter(src, 15, 100, 100) 
cv2.imshow("src", src)
cv2.imshow("blur", dst1)
cv2.imshow("GaussianBlur", dst1)
cv2.imshow("bilateralFilter", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
# 影像雜訊消除_濾波核(捲積核)
# filter2D() 2D濾波核
import cv2
import numpy as np
src = cv2.imread("leclerc_gaussian_noise.png")
# src = cv2.imread("leclerc_salt_pepper_noise.png")
kernel = np.ones((11, 11), np.float32) / 121    # 自訂卷積核
dst = cv2.filter2D(src, -1, kernel)             # 自定義濾波器
cv2.imshow("src", src)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()