In [1]:
# 影像表示方法
# 獲得灰階影像的屬性
import cv2
img = cv2.imread("Building7.jpg", cv2.IMREAD_GRAYSCALE)
print("列印灰階影像的屬性")
print(f"shape = {img.shape}")
print(f"size = {img.size}")
print(f"dtype = {img.dtype}")

列印灰階影像的屬性
shape = (1129, 1693)
size = 1911397
dtype = uint8


In [2]:
# 影像表示方法
# 獲得彩色影像的屬性
import cv2
img = cv2.imread("Building7.jpg")
print("列印彩色影像的屬性")
print(f"shape = {img.shape}")
print(f"size = {img.size}")
print(f"dtype = {img.dtype}")

列印彩色影像的屬性
shape = (1129, 1693, 3)
size = 5734191
dtype = uint8


In [3]:
# 影像表示方法
# 讀取灰階影像特定座標像素的灰階數值
import cv2
pt_y = 169
pt_x = 118
img = cv2.imread("Building7.jpg", cv2.IMREAD_GRAYSCALE)
px = img[pt_y, pt_x]
print(type(px))
print(f"灰階數值 = {px}")

<class 'numpy.uint8'>
灰階數值 = 149


In [4]:
# 影像表示方法
# 讀取彩色影像特定座標像素的BGR數值
import cv2
pt_y = 169
pt_x = 118
img = cv2.imread("Building7.jpg")
px = img[pt_y, pt_x]
print(type(px))
print(f"BGR 數值 = {px}")

<class 'numpy.ndarray'>
BGR 數值 = [248 169  72]


In [5]:
# 影像表示方法
# 讀取彩色影像特定座標像素的各通道數值
import cv2
pt_y = 169
pt_x = 118
img = cv2.imread("Building7.jpg")
blue = img[pt_y, pt_x, 0]
green = img[pt_y, pt_x, 1]
red = img[pt_y, pt_x, 2]
print(f"BGR 數值 = [{blue} {green} {red}]")

BGR 數值 = [248 169 72]


In [6]:
# 影像表示方法
# 修改彩色影像特定座標像素的BGR數值
import cv2
pt_y = 169
pt_x = 118
img = cv2.imread("Building7.jpg")
print(f"更改前 BGR 數值 = {img[pt_y, pt_x]}")
img[pt_y, pt_x] = [255, 255, 255]
print(f"更改後 BGR 數值 = {img[pt_y, pt_x]}")

更改前 BGR 數值 = [248 169  72]
更改後 BGR 數值 = [255 255 255]


In [7]:
# 影像表示方法
# 修改彩色影像特定區塊像素的BGR數值
import cv2
img = cv2.imread("Building7.jpg")
cv2.namedWindow("Before the change", cv2.WINDOW_NORMAL)
cv2.namedWindow("After the change", cv2.WINDOW_NORMAL)
cv2.imshow("Before the change", img)
for y in range(img.shape[0]-50, img.shape[0]):
    for x in range(img.shape[1]-50, img.shape[1]):
        img[y, x] = [255, 255, 255]
cv2.imshow("After the change", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# 影像表示方法
# BGR → RGB 色彩空間轉換範例
import cv2
img = cv2.imread("view.jpg")
print(img[0][0])
cv2.imshow("BGR", img)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print(img_rgb[0][0])
cv2.imshow("RGB", img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

[16 37 39]
[39 37 16]


In [9]:
# 影像表示方法
# BGR → RGB 色彩空間轉換範例
import cv2
img = cv2.imread("view.jpg")
print(img[0][0])
# 若採用這個色彩空間轉換碼，
# 會產生什麼結果？
cv2.imshow("BGR", img)
img_rgb = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
print(img_rgb[0][0])
cv2.imshow("RGB", img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

[16 37 39]
[39 37 16]


In [1]:
# 影像表示方法
# BGR → RGB→BGR色彩空間轉換範例
import cv2
img = cv2.imread("view.jpg")
print(img[0][0])
cv2.imshow("BGR", img)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print(img_rgb[0][0])
cv2.imshow("RGB", img_rgb)
img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
print(img_bgr[0][0])
cv2.imshow("BGR Again", img_bgr)
cv2.waitKey(0)
cv2.destroyAllWindows()

[16 37 39]
[39 37 16]
[16 37 39]


In [2]:
# 影像表示方法
# BGR → 灰階色彩空間轉換範例
import cv2
img = cv2.imread("view.jpg")
print(img[0][0])
print(int(0.299 * img[0][0][2] + 0.587 * img[0][0][1] + 0.114 * img[0][0][0]))
cv2.imshow("BGR", img)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img_gray[0][0])
cv2.imshow("GRAY", img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

[16 37 39]
35
35


In [1]:
# 影像表示方法
# BGR → 灰階→ BGR 色彩空間轉換範例
import cv2
img = cv2.imread("view.jpg")
print(img[0][0])
cv2.imshow("BGR", img)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img_gray[0][0])
cv2.imshow("GRAY", img_gray)
img_bgr = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2BGR)
print(img_bgr[0][0])
cv2.imshow("BGR Again", img_bgr)
cv2.waitKey(0)
cv2.destroyAllWindows()

[16 37 39]
35
[35 35 35]


In [2]:
# 影像表示方法
# BGR → HSV 色彩空間轉換範例
import cv2
img = cv2.imread("mountain.jpg")
print(img[0][0])
cv2.imshow("BGR", img)
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print(img_hsv[0][0])
cv2.imshow("HSV", img_hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

[250 252 252]
[ 30   2 252]


In [1]:
# 影像表示方法
# 拆分BGR 色彩通道範例
import cv2
img = cv2.imread('colorbar.jpg')
print(f"影像 shape 屬性 = {img.shape}")
cv2.imshow('bgr', img)
blue, green, red = cv2.split(img)
cv2.imshow('blue', blue)
cv2.imshow('green', green)
cv2.imshow('red', red)
print(f"B 通道影像 shape 屬性 = {blue.shape}")
cv2.waitKey(0)
cv2.destroyAllWindows()

影像 shape 屬性 = (319, 279, 3)
B 通道影像 shape 屬性 = (319, 279)


In [2]:
# 影像表示方法
# 拆分BGR 色彩通道範例
import cv2
image = cv2.imread('mountain.jpg')
cv2.imshow('bgr', image)
blue, green, red = cv2.split(image) 
cv2.imshow('blue', blue)
cv2.imshow('green', green)
cv2.imshow('red', red)
print(f"BGR 影像 shape 屬性：{image.shape}")
print(f"B 通道影像 shape 屬性：{blue.shape}")
print(f"G 通道影像 shape 屬性：{green.shape}")
print(f"R 通道影像 shape 屬性：{red.shape}")
cv2.waitKey(0)
cv2.destroyAllWindows()

BGR 影像 shape 屬性：(314, 425, 3)
B 通道影像 shape 屬性：(314, 425)
G 通道影像 shape 屬性：(314, 425)
R 通道影像 shape 屬性：(314, 425)


In [1]:
# 影像表示方法
# 拆分BGR 色彩通道範例
import cv2
image = cv2.imread('mountain.jpg')
cv2.imshow('bgr', image)
blue, green, red = cv2.split(image)
cv2.imshow('blue', blue)
cv2.imshow('green', green)
cv2.imshow('red', red)
print(f"BGR 影像：{image[157][212]}")
print("B 通道內容：")
print(blue[157][212])
print("G 通道內容：")
print(green[157][212])
print("R 通道內容：")
print(red[157][212])
cv2.waitKey(0)
cv2.destroyAllWindows()

BGR 影像：[174 226 239]
B 通道內容：
174
G 通道內容：
226
R 通道內容：
239


In [2]:
# 影像表示方法
# 拆分HSV 色彩通道範例
import cv2
image = cv2.imread('mountain.jpg')
cv2.imshow('bgr', image)
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
hue, saturation, value = cv2.split(hsv_image)
cv2.imshow('hsv', hue)
cv2.imshow('saturation', saturation)
cv2.imshow('value', value)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# 影像表示方法
# 合併BGR 色彩通道範例
import cv2
img = cv2.imread('street.jpg')
cv2.imshow("Original", img)
blue, green, red = cv2.split(img)
bgr_img = cv2.merge([blue, green, red])
cv2.imshow("B -> G -> R", bgr_img)
rgb_img = cv2.merge([red, green, blue])
cv2.imshow("R -> G -> B", rgb_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 影像表示方法
# 合併HSV 色彩通道範例
import cv2
img = cv2.imread('street.jpg')
cv2.imshow("Original", img)
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.imshow("HSV", hsv_img)
hue, saturation, value = cv2.split(hsv_img)
hsv_img = cv2.merge([hue, saturation, value])
cv2.imshow("Merge", hsv_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# 影像表示方法
# 色調Hue 調整
import cv2
image = cv2.imread('street.jpg')
cv2.imshow("Original", image)
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
hue, saturation, value = cv2.split(hsv_image)
hue[:, :] = 50 # equivalent to hue.fill(50)
hsv_image1 = cv2.merge([hue, saturation, value])
new_image1 = cv2.cvtColor(hsv_image1, cv2.COLOR_HSV2BGR)
cv2.imshow("New 1", new_image1)
hue[:, :] = 150
hsv_image2 = cv2.merge([hue, saturation, value])
new_image2 = cv2.cvtColor(hsv_image2, cv2.COLOR_HSV2BGR)
cv2.imshow("New 2", new_image2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 影像表示方法
# 飽和度Saturation 調整
import cv2
image = cv2.imread('street.jpg')
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
hue, saturation, value = cv2.split(hsv_image)
saturation.fill(255)
hsv_image = cv2.merge([hue, saturation, value])
new_image = cv2.cvtColor(hsv_image, cv2.COLOR_HSV2BGR)
cv2.imshow("Original", image)
cv2.imshow("New", new_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# 影像表示方法
# 明度Value 調整
import cv2
image = cv2.imread('street.jpg')
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
hue, saturation, value = cv2.split(hsv_image)
value.fill(255)
hsv_image = cv2.merge([hue, saturation, value])
new_image = cv2.cvtColor(hsv_image, 
cv2.COLOR_HSV2BGR)
cv2.imshow("Original", image)
cv2.imshow("New", new_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 影像表示方法
# alpha 通道範例
import cv2
image = cv2.imread('street.jpg')
cv2.imshow("Original", image)
bgra_image = cv2.cvtColor(image, cv2.COLOR_BGR2BGRA)
b, g, r, a = cv2.split(bgra_image)
print("列出轉成含 A 通道影像物件後的 alpha 值")
print(a)
a[:, :] = 32 # equivalent to a.fill(50)
a32_image = cv2.merge([b, g, r, a])
cv2.imshow("The a32 Image", a32_image)
a.fill(128)
a128_image = cv2.merge([b, g, r, a])
cv2.imshow("The a128 Image", a128_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('a32.png', a32_image)
cv2.imwrite('a128.png', a128_image)

列出轉成含 A 通道影像物件後的 alpha 值
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


True