In [1]:
import cv2

cv2.__version__


'4.12.0'

In [2]:
import cv2

img = cv2.imread('coca-cola-logo.png')

#觀察回傳的資料型態
print(type(img))

#觀察回穿的資料內容
print(img)

#觀察回傳的資料形狀
print(img.shape)

<class 'numpy.ndarray'>
[[[ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]
  ...
  [ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]]

 [[ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]
  ...
  [ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]]

 [[ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]
  ...
  [ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]]

 ...

 [[ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]
  ...
  [ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]]

 [[ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]
  ...
  [ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]]

 [[ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]
  ...
  [ 21   4 199]
  [ 21   4 199]
  [ 21   4 199]]]
(700, 700, 3)


In [2]:
import cv2

img = cv2.imread('coca-cola-logo.png')

cv2.imshow("MyPicture", img)
ret_value = cv2.waitKey(5000)  # 0是無限等待，5000是等待5秒
cv2.destroyWindow("MyPicture")
cv2.destroyAllWindows()

In [3]:
import cv2

img = cv2.imread('coca-cola-logo.png')

cv2.imshow("MyPicture", img)
ret_value = cv2.waitKey(5000)  # 0是無限等待，5000是等待5秒
cv2.destroyWindow("MyPicture")
print(f"ret_value: {ret_value}")

ret_value: -1


In [4]:
import cv2

# 設定可調視窗
cv2.namedWindow("MyPicture1")
cv2.namedWindow("MyPicture2", cv2.WINDOW_NORMAL)

img1 = cv2.imread('coca-cola-logo.png')
img2 = cv2.imread('coca-cola-logo.png', cv2.IMREAD_GRAYSCALE)

cv2.imshow("MyPicture1", img1)
cv2.imshow("MyPicture2", img2)

ret_value = cv2.waitKey(0)  # 0是無限等待，5000是等待5秒

cv2.destroyAllWindows()

In [1]:
import cv2

img = cv2.imread('coca-cola-logo.png')

cv2.imshow("MyPicture", img)
ret_value = cv2.waitKey(0)  # 0是無限等待，5000是等待5秒
while ret_value != ord("q"):  # 按下q鍵退出
    ret_value = cv2.waitKey(0)  # 等待按鍵輸入
cv2.destroyWindow("MyPicture")
cv2.destroyAllWindows()

In [3]:
import cv2


cv2.namedWindow("MyPicture")
img = cv2.imread('coca-cola-logo.png')
cv2.imshow("MyPicture", img)

# 儲存圖片
# 將圖片儲存為coca-cola-logo-copy.jpg
ret = cv2.imwrite('coca-cola-logo-copy.jpg', img)

# 檢查儲存是否成功
if ret:
    print("儲存檔案成功!")
else:
    print("儲存檔案失敗!")

cv2.waitKey(0)  # 等待按鍵輸入
cv2.destroyWindow("MyPicture")
cv2.destroyAllWindows()


儲存檔案成功!
