In [50]:
import cv2
import numpy as np

img = cv2.imread('mountain.jpg')
copy_img = img.copy()
hsv_img = cv2.cvtColor(copy_img, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(hsv_img)



In [57]:
if np.any(h <= 0):
    print("小於0")
else:
    h[:, :] -= 5
    print("減5")

print(h)

小於0
[[ 30  54  30 ...   0   0   0]
 [ 26   6   4 ...   0   0   0]
 [  0   0   4 ...   0   0   0]
 ...
 [154 102 129 ...  87 104   0]
 [171 112 116 ...  84  89   0]
 [ 90 102 109 ...  84  89   0]]


In [60]:
if np.any(h >= 179):
    print("大於179")
else:
    h[:, :] += 5
    print("加5")

print(h)

大於179
[[ 30  54  30 ...   0   0   0]
 [ 26   6   4 ...   0   0   0]
 [  0   0   4 ...   0   0   0]
 ...
 [154 102 129 ...  87 104   0]
 [171 112 116 ...  84  89   0]
 [ 90 102 109 ...  84  89   0]]
