In [ ]:
# 影像操作與運算
# 自創灰階影像與編輯
import numpy as np

image = np.zeros((5, 12), np.uint8)
print(f"修改前 image = \n{image}")
print(f"image[1, 4] = {image[1, 4]}")
print("=======分隔線=======")
image[1, 4] = 255
print(f"修改后 image = \n{image}")
print(f"image[1, 4] = {image[1, 4]}")

修改前 image = 
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
image[1, 4] = 0
=======分隔線=======
修改后 image = 
[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]]
image[1, 4] = 255


In [1]:
# 影像操作與運算
# 讀取灰階影像與編輯
import cv2

img = cv2.imread("leclerc_small.png", cv2.IMREAD_GRAYSCALE)
cv2.namedWindow("Before image", cv2.WINDOW_NORMAL)
cv2.imshow("Before image", img)
for i in range(70, 80):
    for j in range(130, 200):
        img[i, j] = 255
cv2.namedWindow("After image", cv2.WINDOW_NORMAL)
cv2.imshow("After image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 影像操作與運算
# 自創彩色影像與編輯
import numpy as np

# 彩色影像陣列Blue
blue_img = np.zeros((2, 3, 3), np.uint8)
blue_img[:, :, 0] = 255
print(f"Blue = \n{blue_img}")

# 彩色影像陣列Green
green_img = np.zeros((2, 3, 3), np.uint8)
green_img[:, :, 1] = 255
print(f"Green = \n{green_img}")

# 彩色影像陣列Red
red_img = np.zeros((2, 3, 3), np.uint8)
red_img[:, :, 2] = 255
print(f"Red = \n{red_img}")


Blue = 
[[[255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]]
Green = 
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
Red = 
[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


In [2]:
# 影像操作與運算
# 自創影像與顯示
import cv2
import numpy as np

blue_img = np.zeros((100, 150, 3), np.uint8)
blue_img[:, :, 0] = 255
print(f"blue_img = \n{blue_img}]")
cv2.imshow("blue_img", blue_img)

green_img = np.zeros((100, 150, 3), np.uint8)
green_img[:, :, 1] = 255
print(f"green_img = \n{green_img}")
cv2.imshow("green_img", green_img)

red_img = np.zeros((100, 150, 3), np.uint8)
red_img[:, :, 2] = 255
print(f"red_img = \n{red_img}")
cv2.imshow("red_img", red_img)

cv2.waitKey(0)
cv2.destroyAllWindows()


blue_img = 
[[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]]
green_img = 
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255

In [3]:
# 影像操作與運算
# 自創彩色影像與編輯
import numpy as np

blue = np.zeros((2, 3, 3), np.uint8)
blue[:, :, 0] = 255
print(f"blue = \n{blue}")
print(f"blue[0, 1] = {blue[0, 1]}")

blue[0, 1] = [50, 100, 150]
print("修訂後")
print(f'blue =\n{blue}')

blue = 
[[[255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]]
blue[0, 1] = [255   0   0]
修訂後
blue =
[[[255   0   0]
  [ 50 100 150]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]]


In [4]:
# 影像操作與運算
# 自創彩色影像與編輯
import numpy as np

# 建立藍色blue底的彩色影像陣列
blue = np.zeros((2, 3, 3), np.uint8)
blue[:, :, 0] = 255
print(f"blue = \n{blue}")
print(f"blue[0, 1, 2] = {blue[0, 1, 2]}")

blue[0, 1, 2] = 50
print("修訂後")
print(f'blue =\n{blue}')
print(f"blue[0, 1, 2] = {blue[0, 1, 2]}")

blue = 
[[[255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]]
blue[0, 1, 2] = 0
修訂後
blue =
[[[255   0   0]
  [255   0  50]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]]
blue[0, 1, 2] = 50


In [5]:
# 影像操作與運算
# 自創彩色影像與編輯
import cv2

img = cv2.imread("leclerc_small.png")
cv2.imshow("Before", img)
print(f"修改前[65, 165] = \n{img[65, 165]}")
print(f"修改前[75, 165] = \n{img[75, 165]}")
print(f"修改前[85, 165] = \n{img[85, 165]}")

# 紫色長條
for y in range(60, 70):
    for x in range(130, 200):
        img[y, x] = [255, 0, 255]

# 白色長條
img[70:80, 130:200] = 255

# 黃色長條
img[80:90, 130:200] = [0, 255, 255]

cv2.imshow("After", img)
print(f"修改後[65, 165] = \n{img[65, 165]}")
print(f"修改後[75, 165] = \n{img[75, 165]}")
print(f"修改後[85, 165] = \n{img[85, 165]}")

cv2.waitKey(0)
cv2.destroyAllWindows()


修改前[65, 165] = 
[163 186 242]
修改前[75, 165] = 
[143 168 232]
修改前[85, 165] = 
[138 166 227]
修改後[65, 165] = 
[255   0 255]
修改後[75, 165] = 
[255 255 255]
修改後[85, 165] = 
[  0 255 255]


In [6]:
# 影像操作與運算
# 編輯含alpha 通道的彩色影像
import cv2

# 透明度
img = cv2.imread("street.png", cv2.IMREAD_UNCHANGED)
cv2.imshow("Before", img)
print(f"修改前[10, 50] = \n{img[10, 50]}")
print(f"修改前[50, 99] = \n{img[50, 90]}")
print("-"*70)
img[0:200, 0:200, 3] = 128
print(f"修改後[10, 50] = \n{img[10, 50]}")
print(f"修改後[50, 99] = \n{img[50, 90]}")
cv2.imwrite("street128.png", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


修改前[10, 50] = 
[ 27  82 109  32]
修改前[50, 99] = 
[ 65 186 255  32]
----------------------------------------------------------------------
修改後[10, 50] = 
[ 27  82 109 128]
修改後[50, 99] = 
[ 65 186 255 128]


In [7]:
# 影像操作與運算
# ndarray 類別的 item 方法使用範例
import numpy as np
image = np.random.randint(0, 200, size=[3, 5], dtype=np.uint8)
print(f"image = \n{image}")
print(f"修改前image.item(1,3) = {image.item(1, 3)}")
image[1, 3] = 255
print("-"*70)
print(f"修改後image =\n{image}")
print(f"修改後image.item(1,3) = {image.item(1, 3)}")

image = 
[[177 198 149 194  20]
 [190 141 110  45 141]
 [146  59 125 178 130]]
修改前image.item(1,3) = 45
----------------------------------------------------------------------
修改後image =
[[177 198 149 194  20]
 [190 141 110 255 141]
 [146  59 125 178 130]]
修改後image.item(1,3) = 255


In [8]:
# 影像操作與運算
# Numpy 高效率設定元素的方法範例
import cv2
img = cv2.imread("leclerc_small.png")
cv2.imshow("Before modify", img)
print(f"修改前img[65,165] = {img[65, 165]}")
print(f"修改前img[75,165] = {img[75, 165]}")
print(f"修改前img[85,165] = {img[85, 165]}")

 # 紫色長條
img[60:70, 130:200] = [255, 0, 255]
 # 白色長條
for y in range(70, 80):
    for x in range(130, 200):
        for z in range(0, 3):
            img[y, x, z] = 255
 # 黃色長條
for y in range(80, 90):
    for x in range(130, 200):
        img[y, x] = [0, 255, 255]
cv2.imshow("After modify", img)
print(f"修改後img[65,165] = {img[65, 165]}")
print(f"修改後img[75,165] = {img[75, 165]}")
print(f"修改後img[85,165] = {img[85, 165]}")
cv2.waitKey(0)
cv2.destroyAllWindows()

修改前img[65,165] = [163 186 242]
修改前img[75,165] = [143 168 232]
修改前img[85,165] = [138 166 227]
修改後img[65,165] = [255   0 255]
修改後img[75,165] = [255 255 255]
修改後img[85,165] = [  0 255 255]


In [9]:
# 影像操作與運算
# Numpy 高效率設定元素的方法範例
import cv2
img = cv2.imread("street.png", cv2.IMREAD_UNCHANGED)
cv2.imshow("Before modify", img)
print(f"修改前img[10,50] = {img[10, 50]}")
print(f"修改前img[50,99] = {img[50, 99]}")
print("-"*70)
img[0:200, 0:200, 3] = 128
print(f"修改後img[10,50] = {img[10, 50]}")
print(f"修改後img[50,99] = {img[50, 99]}")
cv2.imwrite("street128.png", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

修改前img[10,50] = [ 27  82 109  32]
修改前img[50,99] = [ 19 168 248  32]
----------------------------------------------------------------------
修改後img[10,50] = [ 27  82 109 128]
修改後img[50,99] = [ 19 168 248 128]


In [10]:
# 影像操作與運算
# 影像感興趣區域的範例
import cv2
img = cv2.imread("leclerc_small.png")
cv2.imshow("Original", img)
face = img[5:130, 120:210]
cv2.imshow("Face", face)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 影像操作與運算
# 影像加法運算的範例
import cv2
import numpy as np

src1 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
src2 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
res = cv2.add(src1, src2)
print(f"src1= \n{src1}")
print(f"src2= \n{src2}")
print(f"rec = \n{res}")


src1= 
[[ 17 188  25]
 [228 122  94]
 [154 245 154]]
src2= 
[[196  69  83]
 [235 200 186]
 [242 197 233]]
rec = 
[[213 255 108]
 [255 255 255]
 [255 255 255]]


In [ ]:
# 影像操作與運算
# 影像加法運算的範例
import numpy as np

src1 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
src2 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
res = src1 + src2
print(f"src1= \n{src1}")
print(f"src2= \n{src2}")
print(f"rec = \n{res}")


src1= 
[[148 226 109]
 [ 35 123 122]
 [ 21  29 203]]
src2= 
[[143 211 192]
 [ 25 136 118]
 [ 56 254 111]]
rec = 
[[ 35 181  45]
 [ 60   3 240]
 [ 77  27  58]]


In [11]:
# 影像操作與運算
# 影像遮罩範例
import cv2
import numpy as np

img1 = np.ones((4, 5), dtype=np.uint8) * 8
img2 = np.ones((4, 5), dtype=np.uint8) * 9
mask = np.zeros((4, 5), dtype=np.uint8)
mask[1:3, 1:4] = 255
dst = np.random.randint(0, 256, size=[4, 5], dtype=np.uint8)
print(f"img1= \n{img1}")
print(f"img2= \n{img2}")
print(f"mask = \n{mask}")
print(f"最初值 dst = \n {dst}")
dst = cv2.add(img1, img2, mask=mask)
print(f"結果值 dst = \n{dst}")


img1= 
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
img2= 
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
mask = 
[[  0   0   0   0   0]
 [  0 255 255 255   0]
 [  0 255 255 255   0]
 [  0   0   0   0   0]]
最初值 dst = 
 [[114  71  58  89 154]
 [ 71 116  31  61 183]
 [ 90  83 186  84 172]
 [187  82  15 163 182]]
結果值 dst = 
[[ 0  0  0  0  0]
 [ 0 17 17 17  0]
 [ 0 17 17 17  0]
 [ 0  0  0  0  0]]


In [12]:
# 影像操作與運算
# 影像遮罩範例
import cv2
import numpy as np
img1 = np.zeros((200, 300, 3), np.uint8)
img1[:, :, 1] = 255
cv2.imshow("img1", img1)
img2 = np.zeros((200, 300, 3), np.uint8)
img2[:, :, 2] = 255
cv2.imshow("img2", img2)
m = np.zeros((200, 300, 1), np.uint8)
m[50:150, 100:200, :] = 255
cv2.imshow("mask", m)
img3 = cv2.add(img1, img2)
cv2.imshow("img1 + img2", img3)
img4 = cv2.add(img1, img2, mask=m)
cv2.imshow("img1 + img2 + mask", img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# 影像操作與運算
# 重複曝光範例
import cv2
import numpy as np
src1 = np.ones((2, 3), dtype=np.uint8) * 10
src2 = np.ones((2, 3), dtype=np.uint8) * 50
alpha = 1
beta = 0.5
gamma = 5
print(f"src1 = \n {src1}")
print(f"src2 = \n {src2}")
dst = cv2.addWeighted(src1, alpha, src2, beta, gamma)
print(f"dst = \n {dst}")

src1 = 
 [[10 10 10]
 [10 10 10]]
src2 = 
 [[50 50 50]
 [50 50 50]]
dst = 
 [[40 40 40]
 [40 40 40]]


In [14]:
# 影像操作與運算
# 重複曝光範例
import cv2
src1 = cv2.imread("lake.jpg")
cv2.imshow("lake", src1)
src2 = cv2.imread("geneva.jpg")
cv2.imshow("geneva.jpg", src2)
alpha = 1
beta = 0.2
gamma = 1
dst = cv2.addWeighted(src1, alpha, src2, beta, gamma)
cv2.imshow("lake+geneva", dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
# 影像操作與運算
# 影像的位元運算範例
import cv2
import numpy as np
src1 = np.random.randint(0, 255, (3, 5), dtype=np.uint8)
src2 = np.zeros((3, 5), dtype=np.uint8)
src2[0:2, 0:2] = 255
dst = cv2.bitwise_and(src1, src2)
print(f"src1 = \n {src1}")
print(f"src2 = \n {src2}")
print(f"dst = \n {dst}")

src1 = 
 [[205 239 230 184 214]
 [228  54   2  37 103]
 [  6 116 171  94  86]]
src2 = 
 [[255 255   0   0   0]
 [255 255   0   0   0]
 [  0   0   0   0   0]]
dst = 
 [[205 239   0   0   0]
 [228  54   0   0   0]
 [  0   0   0   0   0]]


In [16]:
# 影像操作與運算
# 使用位元運算進行影像遮罩
import cv2
import numpy as np
src1 = cv2.imread("leclerc_small.png", cv2.IMREAD_GRAYSCALE)
src2 = np.zeros(src1.shape, dtype=np.uint8)
src2[30:260, 70:260] = 255
dst = cv2.bitwise_and(src1, src2)
cv2.imshow("Leclerc", src1)
cv2.imshow("Mask", src2)
cv2.imshow("Result", dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
# 影像操作與運算
# 影像加密與解密的範例
import cv2
import numpy as np
src = cv2.imread("leclerc_small.png")
key = np.random.randint(0, 256, src.shape, np.uint8)
print(src.shape)
cv2.imshow("Leclerc", src)
cv2.imshow("Key", key)
img_encry = cv2.bitwise_xor(src, key)           # 加密
img_decry = cv2.bitwise_xor(key, img_encry)     # 解密
cv2.imshow("Encrytion", img_encry)
cv2.imshow("Decrytion", img_decry)
cv2.waitKey()
cv2.destroyAllWindows()

(330, 330, 3)
