In [2]:
import numpy as np

image = np.zeros((5, 12), np.uint8)
print(f"修改前 image = \n{image}")
print(f"image[1, 4] = {image[1, 4]}")
print("=======分隔線=======")
image[1, 4] = 255
print(f"修改后 image = \n{image}")
print(f"image[1, 4] = {image[1, 4]}")

修改前 image = 
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
image[1, 4] = 0
=======分隔線=======
修改后 image = 
[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0]]
image[1, 4] = 255


In [5]:
import numpy as np

# 彩色影像陣列Blue
blue_img = np.zeros((2, 3, 3), np.uint8)
blue_img[:, :, 0] = 255
print(f"Blue = \n{blue_img}")

# 彩色影像陣列Green
green_img = np.zeros((2, 3, 3), np.uint8)
green_img[:, :, 1] = 255
print(f"Green = \n{green_img}")

# 彩色影像陣列Red
red_img = np.zeros((2, 3, 3), np.uint8)
red_img[:, :, 2] = 255
print(f"Red = \n{red_img}")


Blue = 
[[[255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]]
Green = 
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]]]
Red = 
[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]]]


In [6]:
import cv2
import numpy as np

blue_img = np.zeros((100, 150, 3), np.uint8)
blue_img[:, :, 0] = 255
print(f"blue_img = \n{blue_img}]")
cv2.imshow("blue_img", blue_img)

green_img = np.zeros((100, 150, 3), np.uint8)
green_img[:, :, 1] = 255
print(f"green_img = \n{green_img}")
cv2.imshow("green_img", green_img)

red_img = np.zeros((100, 150, 3), np.uint8)
red_img[:, :, 2] = 255
print(f"red_img = \n{red_img}")
cv2.imshow("red_img", red_img)

cv2.waitKey(0)
cv2.destroyAllWindows()


blue_img = 
[[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]]
green_img = 
[[[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0 255   0]
  [  0 255

In [7]:
import cv2
import numpy as np

src1 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
src2 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
res = cv2.add(src1, src2)
print(f"src1= \n{src1}")
print(f"src2= \n{src2}")
print(f"rec = \n{res}")


src1= 
[[ 17 188  25]
 [228 122  94]
 [154 245 154]]
src2= 
[[196  69  83]
 [235 200 186]
 [242 197 233]]
rec = 
[[213 255 108]
 [255 255 255]
 [255 255 255]]


In [8]:
import numpy as np

src1 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
src2 = np.random.randint(0, 256, size=[3, 3], dtype=np.uint8)
res = src1 + src2
print(f"src1= \n{src1}")
print(f"src2= \n{src2}")
print(f"rec = \n{res}")


src1= 
[[148 226 109]
 [ 35 123 122]
 [ 21  29 203]]
src2= 
[[143 211 192]
 [ 25 136 118]
 [ 56 254 111]]
rec = 
[[ 35 181  45]
 [ 60   3 240]
 [ 77  27  58]]


In [9]:
import cv2
import numpy as np

img1 = np.ones((4, 5), dtype=np.uint8) * 8
img2 = np.ones((4, 5), dtype=np.uint8) * 9
mask = np.zeros((4, 5), dtype=np.uint8)
mask[1:3, 1:4] = 255
dst = np.random.randint(0, 256, size=[4, 5], dtype=np.uint8)
print(f"img1= \n{img1}")
print(f"img2= \n{img2}")
print(f"mask = \n{mask}")
print(f"最初值 dst = \n {dst}")
dst = cv2.add(img1, img2, mask=mask)
print(f"結果值 dst = \n{dst}")


img1= 
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
img2= 
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
mask = 
[[  0   0   0   0   0]
 [  0 255 255 255   0]
 [  0 255 255 255   0]
 [  0   0   0   0   0]]
最初值 dst = 
 [[135  10  38 128  97]
 [216 135 102 184  46]
 [138  32 111 192  31]
 [  5  82 254  46  81]]
結果值 dst = 
[[ 0  0  0  0  0]
 [ 0 17 17 17  0]
 [ 0 17 17 17  0]
 [ 0  0  0  0  0]]


In [10]:
import numpy as np

image = np.random.randint(0, 200, size=[3, 5], dtype=np.uint8)
print(f"image = \n{image}")
print(f"修改前image.item(1, 3) = {image.item(1, 3)}")

image[1, 3] = 255
print("_" * 70)
print(f"修改後image = \n{image}")
print(f"修改後image.item(1, 3) =\n{image.item(1, 3)}")

image = 
[[ 72  89 184 128  68]
 [171 131 198  46 181]
 [137  50 179 192  58]]
修改前image.item(1, 3) = 46
______________________________________________________________________
修改後image = 
[[ 72  89 184 128  68]
 [171 131 198 255 181]
 [137  50 179 192  58]]
修改後image.item(1, 3) =
255
