In [ ]:
# 外接矩形
import cv2

src = cv2.imread("explode1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
# 取得外接矩形,格式為元組(tuple)
rect = cv2.boundingRect(contours[0])
# 列出外接矩形的所有細項
x, y, w, h = rect
print(f"左上角 x = {x}, 左上角 y = {y}")
print(f"矩形寬度 = {w}")
print(f"矩形高度 = {h}")
dst = cv2.rectangle(src, (x, y), (x+w, y+h), (0, 255, 255), 2)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


左上角 x = 66, 左上角 y = 39
矩形寬度 = 178
矩形高度 = 100


In [2]:
# 外接矩形
import cv2
import numpy as np

src = cv2.imread("explode2.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
box = cv2.minAreaRect(contours[0])      # 取得最小外接矩形
print(f"最小外接矩形的中心點、寬、高、旋轉角度 = \n {box}")
points = cv2.boxPoints(box)             # 找出頂點座標
points = np.int32(points)               # 轉為整數
# 調整頂點格式
print(f"轉換後的矩形頂角 = \n {points}")
dst = cv2.drawContours(src, [points], 0, (0, 255, 0), 2)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


最小外接矩形的中心點、寬、高、旋轉角度 = 
 ((154.83755493164062, 88.25508880615234), (91.39300537109375, 174.26780700683594), 56.449337005615234)
轉換後的矩形頂角 = 
 [[ 56  98]
 [202   2]
 [252  78]
 [107 174]]


In [2]:
# 外接圓
import cv2

src = cv2.imread("explode3.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
circle = cv2.minEnclosingCircle(contours[0])        # 取得最小外接圓
print(f"最小外接圓的圓心、半徑 = \n {circle}")
(x, y), radius = circle
center = (int(x), int(y))                           # 圓中心座標取整數
radius = int(radius)                                # 圓半徑取整數
dst = cv2.circle(src, center, radius, (0, 255, 255), 2) # 繪製最小外接圓
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


最小外接圓的圓心、半徑 = 
 ((152.2089080810547, 123.05834197998047), 90.02757263183594)


In [3]:
# 橢圓擬合
import cv2

src = cv2.imread("cloud.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_EXTERNAL,
                               cv2.CHAIN_APPROX_SIMPLE)
ellipse = cv2.fitEllipse(contours[0])           # 取得擬合橢圓
print(f"擬合橢圓的內容 = {ellipse}")
print(f"擬合橢圓的資料型態 = {type(ellipse)}")
print(f"橢圓中心點 = {ellipse[0]}")
print(f"長短軸直徑 = {ellipse[1]}")
print(f"旋轉角度 = {ellipse[2]}")
dst = cv2.ellipse(src, ellipse, (0, 255, 0), 2) # 繪製擬合橢圓
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


擬合橢圓的內容 = ((226.74420166015625, 139.14651489257812), (131.7815399169922, 326.1377868652344), 70.7343978881836)
擬合橢圓的資料型態 = <class 'tuple'>
橢圓中心點 = (226.74420166015625, 139.14651489257812)
長短軸直徑 = (131.7815399169922, 326.1377868652344)
旋轉角度 = 70.7343978881836


In [1]:
# 外接三角形
import cv2
import numpy as np

src = cv2.imread("heart.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
area, triangle = cv2.minEnclosingTriangle(contours[0])  # 取得外接三角形
print(f"三角形面積 = {area}")
print(f"三角形頂點座標資料類型 = {type(triangle)}")
print(f"三角頂點座標 = \n{triangle}")
triangle = np.int32(triangle)                           # 轉整數
dst = cv2.line(src, tuple(triangle[0][0]),
               tuple(triangle[1][0]), (0, 255, 0), 2)
dst = cv2.line(src, tuple(triangle[1][0]),
               tuple(triangle[2][0]), (0, 255, 0), 2)
dst = cv2.line(src, tuple(triangle[0][0]),
               tuple(triangle[2][0]), (0, 255, 0), 2)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


三角形面積 = 15638.060546875
三角形頂點座標資料類型 = <class 'numpy.ndarray'>
三角頂點座標 = 
[[[361.3784   115.48649 ]]

 [[ 63.809917  35.371902]]

 [[176.73334  170.88    ]]]


In [2]:
# 多邊形近似
import cv2

src = cv2.imread("multiple.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
n = len(contours)                                   # 輪廓數量
src1 = src.copy()                                   # 複製src影像
src2 = src.copy()                                   # 複製src影像
for i in range(n):
    approx = cv2.approxPolyDP(contours[i], 3, True) # epsilon = 3
    dst1 = cv2.polylines(src1, [approx], True, (0, 255, 0), 2)  # dst1
    approx = cv2.approxPolyDP(contours[i], 15, True)    # epsilon = 15
    dst2 = cv2.polylines(src2, [approx], True, (0, 255, 0), 2)  # dst2
cv2.imshow("dst1: epsilon = 3", dst1)
cv2.imshow("dst2: epsilon = 15", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
# 直線擬合
import cv2

src = cv2.imread("unregular.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
rows, cols = src.shape[:2]
vx, vy, x, y =cv2.fitLine(contours[0], cv2.DIST_L2, 0, 0.01, 0.01)
# 從陣列中讀取數值，避免警告
vx = vx.item()
vy = vy.item()
x = x.item()
y = y.item()
print(f"共線正規化向量 = {vx}, {vy}")
print(f"直線經過的點 = {x}, {y}")
lefty = int((-x * vy / vx) + y)         #左邊點的y座標
righty = int(((cols - x) * vy / vx) + y)    # 右邊點的y座標
dst = cv2.line(src, (0, lefty), (cols-1, righty), (0, 255, 0), 2)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


共線正規化向量 = 0.9303163886070251, -0.36675795912742615
直線經過的點 = 165.3821563720703, 96.8993148803711


In [2]:
# 凸包
import cv2

src = cv2.imread("heart1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
hull = cv2.convexHull(contours[0])                      # 找出凸包點
dst = cv2.polylines(src, [hull], True, (0, 255, 0), 2)  # 把凸包連線
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 凸包
import cv2

src = cv2.imread("hand1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
hull = cv2.convexHull(contours[0])                      # 找出凸包點
dst = cv2.polylines(src, [hull], True, (0, 255, 0), 2)  # 把凸包連線
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
# 凸包-計算手勢的凸包面積
import cv2

src = cv2.imread("hand1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
hull = cv2.convexHull(contours[0])                      # 找出凸包點
dst = cv2.polylines(src, [hull], True, (0, 255, 0), 2)  # 把凸包連線
cv2.imshow("dst", dst)
convex_area = cv2.contourArea(hull)
print(f"凸包面積 = {convex_area}")
cv2.waitKey(0)
cv2.destroyAllWindows()

凸包面積 = 53848.0


In [1]:
# 凸包-找出手勢的多層凸包
import cv2

src = cv2.imread("hand2.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
n = len(contours)
for i in range(n):
    hull = cv2.convexHull(contours[i])
    dst = cv2.polylines(src, [hull], True, (0, 255, 0), 2)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# 凸缺陷
import cv2

src = cv2.imread("star.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]                                   # 輪廓
hull = cv2.convexHull(contour, returnPoints=False)      # 獲得凸包
defects = cv2.convexityDefects(contour, hull)           # 獲得凸包缺陷
print(f"{defects}")
n = defects.shape[0]                                    # 缺陷數量
print(f"缺陷數量 = {n}")
for i in range(n):
    # s是startPoint, e是endPoint, f是farPoint, d是depth
    s, e, f, d = defects[i, 0]
    start = tuple(contour[s][0])                        # 取得startPoint座標
    end = tuple(contour[e][0])                          # 取得endPoint座標
    far = tuple(contour[f][0])                          # 取得farPoint座標
    dst = cv2.line(src, start, end, [0, 0, 255], 2)         # 凸包連線
    dst = cv2.circle(src, far, 3, [0, 0, 255], -1)      # 繪製farPoint
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[ 186    0  187 7834]]

 [[   0   33   32 7753]]

 [[  33   86   54 7689]]

 [[  86  132  109 7936]]

 [[ 132  186  164 7812]]]
缺陷數量 = 5


In [1]:
# 測試輪廓是否為凸形
import cv2

src = cv2.imread("heart1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
src1 = src.copy()                                           # 複製src影像
hull = cv2.convexHull(contours[0])                          # 獲得凸包頂點座標
dst1 = cv2.polylines(src1, [hull], True, (0, 255, 0), 2)    # 把凸包連線
cv2.imshow("dst1", dst1)
isConvex = cv2.isContourConvex(hull)                        # 是否凸形
print(f"凸包是凸形 = {isConvex}")
src2 = src.copy()                                           # 複製src影像
approx = cv2.approxPolyDP(contours[0], 10, True)            # epsilon=10
dst2 = cv2.polylines(src2, [approx], True, (0, 255, 0), 2)  # 近似多邊形連線
cv2.imshow("dst2 - epsilon = 10", dst2)
isConvex = cv2.isContourConvex(approx)                      # 是否凸形
print(f'近似多邊形是凸形 = {isConvex}')
cv2.waitKey(0)
cv2.destroyAllWindows()


凸包是凸形 = True
近似多邊形是凸形 = False


In [ ]:
# 計算影像任一點到輪廓之間距離
import cv2

src = cv2.imread("heart1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
hull = cv2.convexHull(contours[0])                              # 獲得凸包頂點座標
dst = cv2.polylines(src, [hull], True, (0, 255, 0), 2)          # 將凸包連線
# print(hull)    # 可以用這個指令了解凸包座標點

# 點在凸包線上
pointa = (231, 85)                                              # 點在凸包線上
dist_a = cv2.pointPolygonTest(hull, pointa, True)               # 檢測距離
font = cv2.FONT_HERSHEY_SIMPLEX
pos_a = (236, 95)                                               # 文字輸出位置
dst = cv2.circle(src, pointa, 3, [0, 0, 255], -1)               # 用圓標記點 A
cv2.putText(dst, 'A', pos_a, font, 1, (0, 255, 255), 2)         # 輸出文字 A
print(f"dist_a = {dist_a}")

# 點在凸包內
pointb = (150, 100)                                             # 點在凸包內
dist_b = cv2.pointPolygonTest(hull, pointb, True)               # 檢測距離
font = cv2.FONT_HERSHEY_SIMPLEX
pos_b = (160, 110)                                              # 文字輸出位置
dst = cv2.circle(src, pointb, 3, [0, 0, 255], -1)               # 用圓標記點 B
cv2.putText(dst, 'B', pos_b, font, 1, (255, 0, 0), 2)           # 輸出文字 B
print(f"dist_b = {dist_b}")

# 點在凸包外
pointc = (80, 85)                                               # 點在凸包外
dist_c = cv2.pointPolygonTest(hull, pointc, True)               # 檢測距離
font = cv2.FONT_HERSHEY_SIMPLEX
pos_c = (50, 95)                                                # 文字輸出位置
dst = cv2.circle(src, pointc, 3, [0, 0, 255], -1)               # 用圓標記點 C
cv2.putText(dst, 'C', pos_c, font, 1, (255, 0, 255), 2)         # 輸出文字 C
print(f"dist_c = {dist_c}")

cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

dist_a = -0.0
dist_b = 35.65165808180456
dist_c = -16.829141392239833


In [1]:
# 計算影像任一點到輪廓之間距離
import cv2

src = cv2.imread("heart1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
hull = cv2.convexHull(contours[0])                              # 獲得凸包頂點座標
dst = cv2.polylines(src, [hull], True, (0, 255, 0), 2)          # 將凸包連線
# print(hull)    # 可以用這個指令了解凸包座標點

# 點在凸包線上
pointa = (231, 85)                                              # 點在凸包線上
dist_a = cv2.pointPolygonTest(hull, pointa, False)               # 檢測距離
font = cv2.FONT_HERSHEY_SIMPLEX
pos_a = (236, 95)                                               # 文字輸出位置
dst = cv2.circle(src, pointa, 3, [0, 0, 255], -1)               # 用圓標記點 A
cv2.putText(dst, 'A', pos_a, font, 1, (0, 255, 255), 2)         # 輸出文字 A
print(f"dist_a = {dist_a}")

# 點在凸包內
pointb = (150, 100)                                             # 點在凸包內
dist_b = cv2.pointPolygonTest(hull, pointb, False)               # 檢測距離
font = cv2.FONT_HERSHEY_SIMPLEX
pos_b = (160, 110)                                              # 文字輸出位置
dst = cv2.circle(src, pointb, 3, [0, 0, 255], -1)               # 用圓標記點 B
cv2.putText(dst, 'B', pos_b, font, 1, (255, 0, 0), 2)           # 輸出文字 B
print(f"dist_b = {dist_b}")

# 點在凸包外
pointc = (80, 85)                                               # 點在凸包外
dist_c = cv2.pointPolygonTest(hull, pointc, False)               # 檢測距離
font = cv2.FONT_HERSHEY_SIMPLEX
pos_c = (50, 95)                                                # 文字輸出位置
dst = cv2.circle(src, pointc, 3, [0, 0, 255], -1)               # 用圓標記點 C
cv2.putText(dst, 'C', pos_c, font, 1, (255, 0, 255), 2)         # 輸出文字 C
print(f"dist_c = {dist_c}")

cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

dist_a = 0.0
dist_b = 1.0
dist_c = -1.0


In [1]:
# 寬高比
import cv2

src = cv2.imread("explode1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127,255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
x, y, w, h = cv2.boundingRect(contours[0])           # 建構矩形
dst = cv2.rectangle(src, (x, y), (x+w, y+h), (0, 255, 255), 2)
cv2.imshow("dst", dst)
aspectratio = w / h                                 # 計算寬高比
print(f"寬高比 = {aspectratio}")
cv2.waitKey(0)
cv2.destroyAllWindows()


寬高比 = 1.78


In [2]:
# 輪廓點座標的資料格式
import cv2

src = cv2.imread("explode1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127,255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]                       # 建立輪廓變數
print(f"資料格式 = {type(cnt)}")
print(f"資料維度 = {cnt.ndim}")
print(f"資料長度 = {len(cnt)}")
for i in range(len(cnt)):
    print(cnt[i])                       # 列印座標點
cv2.waitKey(0)
cv2.destroyAllWindows()


資料格式 = <class 'numpy.ndarray'>
資料維度 = 3
資料長度 = 383
[[186  39]]
[[181  44]]
[[180  44]]
[[174  50]]
[[173  50]]
[[167  56]]
[[166  56]]
[[158  64]]
[[157  64]]
[[156  65]]
[[155  65]]
[[154  64]]
[[153  64]]
[[149  60]]
[[148  60]]
[[144  56]]
[[143  56]]
[[139  52]]
[[138  52]]
[[135  49]]
[[135  50]]
[[134  51]]
[[134  52]]
[[133  53]]
[[133  54]]
[[132  55]]
[[132  56]]
[[131  57]]
[[131  58]]
[[130  59]]
[[130  60]]
[[129  61]]
[[129  62]]
[[128  63]]
[[128  65]]
[[127  66]]
[[127  67]]
[[126  68]]
[[125  68]]
[[124  67]]
[[121  67]]
[[120  66]]
[[118  66]]
[[117  65]]
[[115  65]]
[[114  64]]
[[112  64]]
[[111  63]]
[[109  63]]
[[108  62]]
[[106  62]]
[[105  61]]
[[103  61]]
[[102  60]]
[[100  60]]
[[99 59]]
[[97 59]]
[[96 58]]
[[94 58]]
[[93 57]]
[[90 57]]
[[89 56]]
[[87 56]]
[[86 55]]
[[84 55]]
[[83 54]]
[[81 54]]
[[80 53]]
[[78 53]]
[[77 52]]
[[75 52]]
[[74 51]]
[[72 51]]
[[71 50]]
[[70 50]]
[[71 50]]
[[73 52]]
[[74 52]]
[[77 55]]
[[78 55]]
[[80 57]]
[[81 57]]
[[83 59]]
[[84 59]]

In [3]:
# 輪廓點座標的資料格式
# 輪廓的極點:最左邊點、最右邊點、最上方點、最下方點
import cv2

src = cv2.imread("explode1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127,255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(dst_binary,
                               cv2.RETR_LIST,
                               cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]                       # 建立輪廓變數
left = cnt[cnt[:, :, 0].argmin()][0]
right = cnt[cnt[:, :, 0].argmax()][0]
top = cnt[cnt[:, :, 1].argmin()][0]
bottom = cnt[cnt[:, :, 1].argmax()][0]
print(f"最左點 = {left}")
print(f"最右點 = {right}")
print(f"最上點 = {top}")
print(f"最下點 = {bottom}")
dst = cv2.circle(src, left, 5, [255, 0, 0], -1)
dst = cv2.circle(src, right, 5, [0, 255, 0], -1)
dst = cv2.circle(src, top, 5, [0, 255, 255], -1)
dst = cv2.circle(src, bottom, 5, [0, 0, 255], -1)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


最左點 = [66 79]
最右點 = [243  99]
最上點 = [186  39]
最下點 = [136 138]
