#### 幾何形狀的檢測與匹配

#### findContours() 函數是 OpenCV 中用來從二值化影像中尋找輪廓的函數，常用於檢測物體邊界或形狀分析。
#### findContours() 函數說明
* 函數語法（Python）：
        contours, hierarchy = cv2.findContours(image, mode, method)
* 參數說明：
    * image：輸入的二值化圖像（通常是灰階圖經過二值化或 Canny 邊緣檢測後的結果）。該圖像會被修改，若需保留可先複製。
    * mode：輪廓檢索模式，主要有：
        * cv2.RETR_EXTERNAL：只檢測最外層輪廓，忽略子輪廓。
        * cv2.RETR_LIST：檢測所有輪廓但不建立層級關係。
        * cv2.RETR_CCOMP：建立兩層層級結構的輪廓。
        * cv2.RETR_TREE：建立完整的輪廓層級結構（父子孫關係）。
    * method：輪廓逼近方法，常用：
        * cv2.CHAIN_APPROX_NONE：儲存所有輪廓點。
        * cv2.CHAIN_APPROX_SIMPLE：壓縮輪廓點，去除冗餘。
* 回傳值：
    * contours：輪廓列表，每個輪廓是點的 numpy 陣列。
    * hierarchy：輪廓層級信息，描述各輪廓之間的父子關係等。

In [1]:
# 輪廓檢測與繪製的範例- findContours()
import cv2

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
# 影線轉成灰階
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
# 繪製圖形輪廓
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
cv2.imshow("result", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 輪廓檢測與繪製的範例- findContours()
# drawContours() 函式會修改原始影像
import cv2

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
# 影線轉成灰階
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
# 繪製圖形輪廓
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
cv2.imshow("result", dst)
cv2.imshow("src again",)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
# 輪廓檢測與繪製的範例- findContours()
# 觀察輪廓的資料型態、形狀與內容
import cv2

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
# 影線轉成灰階
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)

print(f"資料型態:{type(contours)}")
print(f"輪廓數量:{len(contours)}")
print(f"元素 0 資料型態:{type(contours[0])}")
print(f"元素 1 資料型態:{type(contours[1])}")
print(f"元素 2 資料型態:{type(contours[2])}")
print(f"輪廓:{contours}")


資料型態:<class 'tuple'>
輪廓數量:3
元素 0 資料型態:<class 'numpy.ndarray'>
元素 1 資料型態:<class 'numpy.ndarray'>
元素 2 資料型態:<class 'numpy.ndarray'>
輪廓:(array([[[201,  66]],

       [[201,  67]],

       [[199,  69]],

       [[199,  70]],

       [[198,  71]],

       [[198,  72]],

       [[197,  73]],

       [[197,  74]],

       [[195,  76]],

       [[195,  77]],

       [[194,  78]],

       [[194,  79]],

       [[192,  81]],

       [[192,  82]],

       [[191,  83]],

       [[191,  84]],

       [[190,  85]],

       [[190,  86]],

       [[188,  88]],

       [[188,  89]],

       [[187,  90]],

       [[187,  91]],

       [[186,  92]],

       [[186,  93]],

       [[184,  95]],

       [[184,  96]],

       [[183,  97]],

       [[183,  98]],

       [[182,  99]],

       [[182, 100]],

       [[180, 102]],

       [[180, 103]],

       [[179, 104]],

       [[179, 105]],

       [[177, 107]],

       [[177, 108]],

       [[176, 109]],

       [[176, 110]],

       [[174, 112]],

       [

In [13]:
# 輪廓檢測與繪製的範例- findContours()
# 課堂練習-打上編號
import cv2

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
# 影線轉成灰階
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)

# 繪製圖形輪廓
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)

# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
pin1 = contours[0][0][0]
pin2 = contours[1][0][0]
pin3 = contours[2][0][0]
cv2.putText(dst, '0', pin1, font, 1, (0, 0, 255), 2)
cv2.putText(dst, '1', pin2, font, 1, (0, 0, 255), 2)
cv2.putText(dst, '2', pin3, font, 1, (0, 0, 255), 2)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# print(contours[0][1][0])

In [14]:
# 輪廓檢測與繪製的範例- findContours()
# 課堂練習-打上編號
import cv2

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
# 影線轉成灰階
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
# 二值化處理影像
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
# 找尋影像內的輪廓
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)

# 繪製圖形輪廓
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)

# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)

cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# print(contours[0][1][0])

In [1]:
# 輪廓檢測與繪製
# 以輪廓索引來繪製各個輪廓

import cv2
import numpy as np

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
n = len(contours)                           # 取得輪廓數量
imgList = []                                # 建立輪廓串列
for i in range(n):                          # 依次繪製輪廓
    img = np.zeros(src.shape, np.uint8)     # 建立黑底影像
    imgList.append(img)                     # 將黑底影像加入串列
    # 繪製輪廓影像
    imgList[i] = cv2.drawContours(imgList[i], contours, i, (255, 255, 255), 5)
    cv2.imshow("contours" + str(i), imgList[i])     # 顯示輪廓影像
cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
# 輪廓檢測與繪製
# 計算各種輪廓的數量
import cv2

src = cv2.imread("easy.jpg")
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary, cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
# 初始化統計數據
triangle_count = 0                  # 三角形計數器
rectangle_count = 0                 # 矩形計數器
circle_count = 0                    # 圓形計數器

# 輪廓處理
for i, contour in enumerate(contours):
    # 輪廓近似
    epsilon = 0.02 * cv2.arcLength(contour, True)   # 根據輪廓周長調整
    approx = cv2.approxPolyDP(contour, epsilon, True)

    # 輪廓點數量
    num_points = len(approx)
    # 判斷類型
    if num_points == 3:                             # 三角形
        triangle_count += 1
        print(f"輪廓 {i} : 三角形, 輪廓點數量 = {num_points}")
    elif num_points == 4:                           # 矩形
        print(f"輪廓 {i} : 矩形,   輪廓點數量 = {num_points}")
        rectangle_count += 1
    elif num_points >= 8:                           # 圓形(近似為園)
        circle_count += 1
        print(f"輪廓 {i} : 圓形,   輪廓點數量 = {num_points}")
    else:
        print(f"輪廓 {i} : 其他形狀, 輪廓點數量 = {num_points}")

# 統計結果
print(f"三角形的輪廓總數量 : {triangle_count}")
print(f"矩形的輪廓總數量   : {rectangle_count}")
print(f"圓形的輪廓總數量   : {circle_count}")


輪廓 0 : 三角形, 輪廓點數量 = 3
輪廓 1 : 矩形,   輪廓點數量 = 4
輪廓 2 : 圓形,   輪廓點數量 = 8
三角形的輪廓總數量 : 1
矩形的輪廓總數量   : 1
圓形的輪廓總數量   : 1


In [2]:
# 輪廓檢測與繪製
# 如果輪廓內還有輪廓-RETR_EXTERNAL
import cv2

src = cv2.imread("easy1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)

cv2.imshow("result", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
# 輪廓檢測與繪製
# 如果輪廓內還有輪廓-RETR_LIST
import cv2

src = cv2.imread("easy1.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 輪廓檢測與繪製
# 繪製一般影像的輪廓-RETR_LIST
import cv2

src = cv2.imread("lake.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 150, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 2)
# # 繪製文字
# font = cv2.FONT_HERSHEY_SIMPLEX
# for i in range(len(contours)):
#     cv2.putText(dst, str(i), contours[i][0][0], font, 0.5, (0, 0, 255), 1)
cv2.imshow("result", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# 輪廓檢測與繪製
# 清除天空背景
import cv2

src = cv2.imread("lake.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 150, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (255, 255, 255), -1)
# # 繪製文字
# font = cv2.FONT_HERSHEY_SIMPLEX
# for i in range(len(contours)):
#     cv2.putText(dst, str(i), contours[i][0][0], font, 0.5, (0, 0, 255), 1)
cv2.imshow("result", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# 輪廓檢測與繪製
# 保留天空背景,燈塔以黑色顯示
import cv2
import numpy as np

src = cv2.imread("lake.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, dst_binary = cv2.threshold(src_gray, 150, 255, cv2.THRESH_BINARY)
cv2.imshow("binary", dst_binary)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)
mask = np.zeros(src.shape, np.uint8)
dst = cv2.drawContours(mask, contours, -1, (255, 255, 255), -1)
dst_result = cv2.bitwise_and(src, mask)
# # 繪製文字
# font = cv2.FONT_HERSHEY_SIMPLEX
# for i in range(len(contours)):
#     cv2.putText(dst, str(i), contours[i][0][0], font, 0.5, (0, 0, 255), 1)
cv2.imshow("dst result", dst_result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 輪廓的層級-RETR_EXTERNAL
import cv2

src = cv2.imread("easy2.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)

dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
print(f"輪廓:{contours}")
print(f"輪廓層級的資料型態:{type(hierarchy)}")
print(f"輪廓層級的陣列形狀:\n{hierarchy.shape}")
print(f"輪廓層級的內容:\n{hierarchy}")
cv2.waitKey(0)
cv2.destroyAllWindows()


輪廓:(array([[[ 30,  72]],

       [[ 30, 114]],

       [[106, 114]],

       [[106,  72]]], dtype=int32), array([[[144,  37]],

       [[144, 209]],

       [[320, 209]],

       [[320,  37]]], dtype=int32))
輪廓層級的資料型態:<class 'numpy.ndarray'>
輪廓層級的陣列形狀:
(1, 2, 4)
輪廓層級的內容:
[[[ 1 -1 -1 -1]
  [-1  0 -1 -1]]]


In [1]:
# 輪廓的層級-RETR_LIST
import cv2

src = cv2.imread("easy2.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)

dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
print(f"輪廓:{contours}")
print(f"輪廓層級的資料型態:{type(hierarchy)}")
print(f"輪廓層級的陣列形狀:\n{hierarchy.shape}")
print(f"輪廓層級的內容:\n{hierarchy}")
cv2.waitKey(0)
cv2.destroyAllWindows()


輪廓:(array([[[178,  79]],

       [[179,  78]],

       [[297,  78]],

       [[298,  79]],

       [[298, 197]],

       [[297, 198]],

       [[179, 198]],

       [[178, 197]]], dtype=int32), array([[[ 30,  72]],

       [[ 30, 114]],

       [[106, 114]],

       [[106,  72]]], dtype=int32), array([[[144,  37]],

       [[144, 209]],

       [[320, 209]],

       [[320,  37]]], dtype=int32))
輪廓層級的資料型態:<class 'numpy.ndarray'>
輪廓層級的陣列形狀:
(1, 3, 4)
輪廓層級的內容:
[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [-1  1 -1 -1]]]


In [2]:
# 輪廓的層級-RETR_CCOMP
import cv2

src = cv2.imread("easy2.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_CCOMP,
                                       cv2.CHAIN_APPROX_SIMPLE)

dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
print(f"輪廓:{contours}")
print(f"輪廓層級的資料型態:{type(hierarchy)}")
print(f"輪廓層級的陣列形狀:\n{hierarchy.shape}")
print(f"輪廓層級的內容:\n{hierarchy}")
cv2.waitKey(0)
cv2.destroyAllWindows()


輪廓:(array([[[ 30,  72]],

       [[ 30, 114]],

       [[106, 114]],

       [[106,  72]]], dtype=int32), array([[[144,  37]],

       [[144, 209]],

       [[320, 209]],

       [[320,  37]]], dtype=int32), array([[[178,  79]],

       [[179,  78]],

       [[297,  78]],

       [[298,  79]],

       [[298, 197]],

       [[297, 198]],

       [[179, 198]],

       [[178, 197]]], dtype=int32))
輪廓層級的資料型態:<class 'numpy.ndarray'>
輪廓層級的陣列形狀:
(1, 3, 4)
輪廓層級的內容:
[[[ 1 -1 -1 -1]
  [-1  0  2 -1]
  [-1 -1 -1  1]]]


In [1]:
# 輪廓的層級-RETR_TREE
import cv2

src = cv2.imread("easy2.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ret, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_TREE,
                                       cv2.CHAIN_APPROX_SIMPLE)

dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
print(f"輪廓:{contours}")
print(f"輪廓層級的資料型態:{type(hierarchy)}")
print(f"輪廓層級的陣列形狀:\n{hierarchy.shape}")
print(f"輪廓層級的內容:\n{hierarchy}")
cv2.waitKey(0)
cv2.destroyAllWindows()


輪廓:(array([[[ 30,  72]],

       [[ 30, 114]],

       [[106, 114]],

       [[106,  72]]], dtype=int32), array([[[144,  37]],

       [[144, 209]],

       [[320, 209]],

       [[320,  37]]], dtype=int32), array([[[178,  79]],

       [[179,  78]],

       [[297,  78]],

       [[298,  79]],

       [[298, 197]],

       [[297, 198]],

       [[179, 198]],

       [[178, 197]]], dtype=int32))
輪廓層級的資料型態:<class 'numpy.ndarray'>
輪廓層級的陣列形狀:
(1, 3, 4)
輪廓層級的內容:
[[[ 1 -1 -1 -1]
  [-1  0  2 -1]
  [-1 -1 -1  1]]]


In [1]:
# 影像矩
# 取得輪廓的面積
import cv2
src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
n = len(contours)
for i in range(n):
    M = cv2.moments(contours[i])
    print(f"列印影像矩 {i} \n {M}")         # 列印影像矩
    print(f"輪廓 {i} 面積 = {M['m00']}")    # 列印輪廓面積
cv2.waitKey(0)
cv2.destroyAllWindows()

列印影像矩 0 
 {'m00': 4344.0, 'm10': 875551.0, 'm01': 534872.3333333333, 'm20': 178291996.0, 'm11': 107806662.83333333, 'm02': 67667946.66666666, 'm30': 36669616857.5, 'm21': 21974314231.166668, 'm12': 13638973452.333334, 'm03': 8756666917.5, 'mu20': 1821104.2870626152, 'mu11': 952.3539748340845, 'mu02': 1809656.3891702518, 'mu30': 32430.916221618652, 'mu21': 21016905.17049837, 'mu12': -12999.67679822445, 'mu03': -20861350.522485733, 'nu20': 0.09650619295080995, 'nu11': 5.04683104123893e-05, 'nu02': 0.09589953189865046, 'nu30': 2.6075622006486343e-05, 'nu21': 0.016898346973212075, 'nu12': -1.0452207272856162e-05, 'nu03': -0.01677327544654871}
輪廓 0 面積 = 4344.0
列印影像矩 1 
 {'m00': 7569.0, 'm10': 2599951.5, 'm01': 821236.5, 'm20': 897857487.0, 'm11': 282094737.75, 'm02': 93878307.0, 'm30': 311693885601.75, 'm21': 97417537339.5, 'm12': 32247198454.5, 'm03': 11221786154.25, 'mu20': 4774146.75, 'mu11': 0.0, 'mu02': 4774146.75, 'mu30': 0.0, 'mu21': 0.0, 'mu12': 0.0, 'mu03': 0.0, 'nu20': 0.083333333

In [2]:
# 影像矩
# 取得輪廓的面積-另一種方式
import cv2

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
n = len(contours)
for i in range(n):
    area = cv2.contourArea(contours[i])     # 計算輪廓面積
    print(f"輪廓 {i} 面積 = {area}")
cv2.waitKey(0)
cv2.destroyAllWindows()

輪廓 0 面積 = 4344.0
輪廓 1 面積 = 7569.0
輪廓 2 面積 = 5964.0


In [1]:
# 影像矩
# 取得輪廓的質心
import cv2

src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
for c in contours:                                   # 繪製中心點迴圈
    M = cv2.moments(c)                               # 影像矩
    Cx = int(M["m10"] / M["m00"])                    # 質心 x 座標
    Cy = int(M["m01"] / M["m00"])                    # 質心 y 座標
    cv2.circle(dst, (Cx, Cy), 5, (255, 0, 0), -1)    # 繪製中心點
cv2.imshow("result", dst)                            # 顯示結果影像
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 影像矩
# 取得輪廓的周長
import cv2
src = cv2.imread("easy.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_EXTERNAL,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
font = cv2.FONT_HERSHEY_SIMPLEX
n = len(contours)
for i in range(n):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
    area = cv2.arcLength(contours[i], True)     # 計算輪廓周長
    print(f"輪廓 {i} 周長 = {area}")
cv2.imshow("result", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

輪廓 0 周長 = 315.4213538169861
輪廓 1 周長 = 348.0
輪廓 2 周長 = 289.42135322093964


In [2]:
# Hu 矩
# 具有平移、縮放時保持不變的特性
import cv2
src = cv2.imread("3heart.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
M0 = cv2.moments(contours[0])           # 計算編號 0 影像矩
M1 = cv2.moments(contours[1])           # 計算編號 1 影像矩
M2 = cv2.moments(contours[2])           # 計算編號 2 影像矩
Hu0 = cv2.HuMoments(M0)                 # 計算編號 0 Hu 矩
Hu1 = cv2.HuMoments(M1)                 # 計算編號 1 Hu 矩
Hu2 = cv2.HuMoments(M2)                 # 計算編號 2 Hu 矩
# 列印 Hu 矩
print(f"h0 = {Hu0[0]}\t\t {Hu1[0]}\t\t {Hu2[0]}")
print(f"h1 = {Hu0[1]}\t\t {Hu1[1]}\t\t {Hu2[1]}")
print(f"h2 = {Hu0[2]}\t\t {Hu1[2]}\t\t {Hu2[2]}")
print(f"h3 = {Hu0[3]}\t\t {Hu1[3]}\t {Hu2[3]}")
print(f"h4 = {Hu0[4]}\t\t {Hu1[4]}\t {Hu2[4]}")
print(f"h5 = {Hu0[5]}\t\t {Hu1[5]}\t {Hu2[5]}")
print(f"h6 = {Hu0[6]}\t\t {Hu1[6]}\t {Hu2[6]}")
cv2.waitKey(0)
cv2.destroyAllWindows()

h0 = [0.18400164]		 [0.18362647]		 [0.18362647]
h1 = [0.00390046]		 [0.00388969]		 [0.00388969]
h2 = [0.00118707]		 [0.00115877]		 [0.00115877]
h3 = [4.41012234e-05]		 [4.27240647e-05]	 [4.27240647e-05]
h4 = [-1.00904583e-08]		 [-9.50599826e-09]	 [-9.50599826e-09]
h5 = [-2.75427701e-06]		 [-2.66455047e-06]	 [-2.66455047e-06]
h6 = [4.40391468e-11]		 [6.22527623e-11]	 [6.22527623e-11]


In [1]:
# Hu 矩
# 具有平移、縮放時保持不變的特性
import cv2
src = cv2.imread("3shapes.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)
M0 = cv2.moments(contours[0])           # 計算編號 0 影像矩
M1 = cv2.moments(contours[1])           # 計算編號 1 影像矩
M2 = cv2.moments(contours[2])           # 計算編號 2 影像矩
Hu0 = cv2.HuMoments(M0)                 # 計算編號 0 Hu 矩
Hu1 = cv2.HuMoments(M1)                 # 計算編號 1 Hu 矩
Hu2 = cv2.HuMoments(M2)                 # 計算編號 2 Hu 矩
# 列印 Hu 矩
print(f"h0 = {Hu0[0]}\t\t {Hu1[0]}\t\t {Hu2[0]}")
print(f"h1 = {Hu0[1]}\t\t {Hu1[1]}\t\t {Hu2[1]}")
print(f"h2 = {Hu0[2]}\t\t {Hu1[2]}\t\t {Hu2[2]}")
print(f"h3 = {Hu0[3]}\t\t {Hu1[3]}\t {Hu2[3]}")
print(f"h4 = {Hu0[4]}\t\t {Hu1[4]}\t {Hu2[4]}")
print(f"h5 = {Hu0[5]}\t\t {Hu1[5]}\t {Hu2[5]}")
print(f"h6 = {Hu0[6]}\t\t {Hu1[6]}\t {Hu2[6]}")
cv2.waitKey(0)
cv2.destroyAllWindows()

h0 = [0.18362125]		 [0.15949742]		 [0.18383141]
h1 = [0.00388853]		 [6.2205636e-05]		 [0.00388999]
h2 = [0.00115914]		 [1.09030421e-09]		 [0.00117116]
h3 = [4.25428614e-05]		 [8.53260565e-13]	 [4.34904474e-05]
h4 = [-9.44727464e-09]		 [1.09940012e-23]	 [-9.81486955e-09]
h5 = [-2.6528849e-06]		 [1.82308256e-16]	 [-2.7123853e-06]
h6 = [2.90666076e-11]		 [2.35891942e-23]	 [8.19693167e-11]


In [1]:
# Hu 矩
# 輪廓匹配
import cv2

src = cv2.imread("myheart.jpg")
cv2.imshow("src", src)
src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
_, dst_binary = cv2.threshold(src_gray, 127, 255, cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(dst_binary,
                                       cv2.RETR_LIST,
                                       cv2.CHAIN_APPROX_SIMPLE)
dst = cv2.drawContours(src, contours, -1, (0, 255, 0), 5)
# 繪製文字
font = cv2.FONT_HERSHEY_SIMPLEX
for i in range(len(contours)):
    cv2.putText(dst, str(i), contours[i][0][0], font, 1, (0, 0, 255), 2)
cv2.imshow("result", dst)

match0 = cv2.matchShapes(contours[0], contours[0], 1, 0) # 輪廓0和0比較
print(f"輪廓0和0比較 = {match0}")
match1 = cv2.matchShapes(contours[0], contours[1], 1, 0) # 輪廓0和1比較
print(f"輪廓0和1比較 = {match1}")
match2 = cv2.matchShapes(contours[0], contours[2], 1, 0) # 輪廓0和2比較
print(f"輪廓0和2比較 = {match2}")
cv2.waitKey(0)
cv2.destroyAllWindows()

輪廓0和0比較 = 0.0
輪廓0和1比較 = 0.00046299603915214704
輪廓0和2比較 = 0.29307592277155203
