In [ ]:
# 閾值處理
# threshold()
import cv2
import numpy as np

thresh = 127
maxval = 255
src = np.random.randint(0, 256, size=[3,5], dtype=np.uint8)
ret, dst = cv2.threshold(src, thresh, maxval, cv2.THRESH_BINARY)
print(f"src = \n {src}")
print(f"threshold = {ret}")
print(f"dst =\n {dst}")


src = 
 [[ 79 218 237 221 211]
 [188  36 177  77  59]
 [222  19  20 119 147]]
threshold = 127.0
dst =
 [[  0 255 255 255 255]
 [255   0 255   0   0]
 [255   0   0   0 255]]


In [ ]:
# 閾值處理
# threshold() Otsu演算法
import cv2

src = cv2.imread("leclerc.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("Src", src)
thresh = 100
maxval = 255
ret, dst = cv2.threshold(src, thresh, maxval, cv2.THRESH_BINARY)
cv2.imshow("Dst - 100", dst)
thresh = 0
ret, dst = cv2.threshold(
    src, thresh, maxval, cv2.THRESH_BINARY+cv2.THRESH_OTSU
)
cv2.imshow("Dst - Otsu", dst)
print(f"threshold = {ret}")
cv2.waitKey(0)
cv2.destroyAllWindows()


threshold = 123.0


In [ ]:
# 閾值處理
# adaptiveThreshold() 自適應閾值應用
import cv2

src = cv2.imread("school.jpg", cv2.IMREAD_GRAYSCALE)
thresh = 127
maxval = 255
ret, dst = cv2.threshold(src, thresh, maxval, cv2.THRESH_BINARY)
# 自適應閾值計算方式為ADAPTIVE_THRESH_MEAN_C
dst_mean = cv2.adaptiveThreshold(src, maxval, cv2.ADAPTIVE_THRESH_MEAN_C,
                                 cv2.THRESH_BINARY, 3, 5)
# 自適應閾值計算方式為ADAPTIVE_THRESH_GAUSSIAN_C
dst_gauss = cv2.adaptiveThreshold(src, maxval, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                 cv2.THRESH_BINARY, 3, 5)
cv2.imshow("src", src)
cv2.imshow("THRESH_BINARY", dst)
cv2.imshow("ADAPTIVE_THRESH_MEAN_C", dst_mean)
cv2.imshow("ADAPTIVE_THRESH_GAUSSIAN_C", dst_gauss)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 閾值處理
# 平面圖分解
import cv2
import numpy as np

img = cv2.imread("leclerc.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("Leclerc.png", img)
row, column = img.shape
x = np.zeros((row, column, 8), dtype=np.uint8)
for i in range(8):
    x[:, :, i] = 2**i
result = np.zeros((row,column, 8), dtype=np.uint8)
for i in range(8):
    result[:, :, i] = cv2.bitwise_and(img, x[:, :, i])
    # mask = result[:, :, i] > 0
    # result[mask] = 255
    ret, result[:, :, i] = cv2.threshold(result[:, :, i], 0, 255, cv2.THRESH_BINARY)
    cv2.imshow(str(i), result[:, :, i])

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 閾值處理
# 最低有效位元對影像整體沒有太大的影響
import cv2
import numpy as np

img = cv2.imread("leclerc.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("Leclerc.png", img)

row, column = img.shape
mask = np.random.randint(254, 256, (row, column)).astype(np.uint8)
cv2.imshow("mask", mask)
new_img = cv2.bitwise_and(img, mask)
cv2.imshow("New Leclerc", new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 閾值處理
# 把浮水印影像嵌入原始影像
import cv2
import numpy as np

img = cv2.imread("leclerc.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("Leclerc.png", img)
row, column = img.shape
high7 = np.ones((row, column), np.uint8) * 254
tmp_img = cv2.bitwise_and(img, high7)

watermark = np.ones((row, column), np.uint8) * 255
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(watermark, 'Copy Right', (10, row - 10), font, 1, 0, 2)
cv2.imshow("Copy Right", watermark)
ret, wm = cv2.threshold(watermark, 0, 1, cv2.THRESH_BINARY)
new_img = cv2.bitwise_or(tmp_img, wm)
cv2.imshow("New Leclerc", new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
# 閾值處理-影像分割
import cv2

src = cv2.imread('coin.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow("Src", src)
ret, dst = cv2.threshold(src, 240, 255, cv2.THRESH_BINARY_INV)
# ret, dst = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)
print("Threshold = ", ret)
cv2.imshow("Dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


Threshold =  240.0


In [3]:
# 閾值處理-多個物件的影像分割
import cv2
src = cv2.imread("coin1.jpg", cv2.IMREAD_GRAYSCALE)
cv2.imshow("Src", src)
ret, dst = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)
print("Threshold = ", ret)
cv2.imshow("Dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

Threshold =  117.0
