In [ ]:
import cv2
import numpy as np

src = cv2.imread("leclerc_small.png")
pt_y = src.shape[0]
pt_x = src.shape[1]
h = pt_y // 2
w = pt_x // 2
key = np.random.randint(0, 256, [h, w, 3], np.uint8)

src_encry = [(0, 0),
             (0, pt_x - w),
             (pt_y - h, 0),
             (pt_y - h, pt_x - w)
             ]

for i, j in src_encry:
    src[i:i+h, j:j+w] = key



[[[ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]
  ...
  [ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]]

 [[ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]
  ...
  [ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]]

 [[ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]
  ...
  [ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]]

 ...

 [[ 29  20  25]
  [ 29  20  25]
  [ 29  20  25]
  ...
  [ 29  20  25]
  [ 29  20  25]
  [ 29  20  25]]

 [[ 29  20  25]
  [ 29  20  25]
  [ 29  20  25]
  ...
  [ 29  20  25]
  [ 29  20  25]
  [ 29  20  25]]

 [[ 29  20  25]
  [ 29  20  25]
  [ 29  20  25]
  ...
  [ 29  20  25]
  [ 29  20  25]
  [ 29  20  25]]]
[[[196 148  90]
  [174 142  97]
  [ 54 165 108]
  ...
  [ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]]

 [[177  38 227]
  [146 109 132]
  [146 116 226]
  ...
  [ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]]

 [[127 141  95]
  [239 111  48]
  [241 154 162]
  ...
  [ 48  17 233]
  [ 48  17 233]
  [ 48  17 233]]

 ...

 [[ 29  20  25]
  [ 29  20  25]
  [ 29  20  25]
  ..

In [31]:
key = np.random.randint(0, 256, [2, 2, 3], np.uint8)
print(key)
key_add = key * key

print(key_add)

[[[ 93  52 208]
  [195 194 160]]

 [[122 146  84]
  [ 89   5 191]]]
[[[201 144   0]
  [137   4   0]]

 [[ 36  68 144]
  [241  25 129]]]
