In [ ]:
# 影像縮放(提供長寬尺寸)
import cv2

src = cv2.imread('southpole.jpg')
cv2.imshow('Src', src)
width = 300
height = 200
dsize = (width, height)
dst = cv2.resize(src, dsize)
cv2.imshow('Dst', dst)
print(f'src.shape = {src.shape}')
print(f'dst.shape = {dst.shape}')
cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
# 影像縮放(fx,fy的比例縮放)
import cv2

src = cv2.imread('southpole.jpg')
cv2.imshow('Src', src)
dst = cv2.resize(src, None, fx=0.5, fy=1.1)
cv2.imshow('Dst', dst)
print(f'src.shape = {src.shape}')
print(f'dst.shape = {dst.shape}')
cv2.waitKey(0)
cv2.destroyAllWindows()


src.shape = (269, 523, 3)
dst.shape = (296, 262, 3)


In [ ]:
# 影像翻轉
import cv2

src = cv2.imread('python.jpg')
cv2.imshow('Src', src)

# 上下翻轉
dst1 = cv2.flip(src, 0)
cv2.imshow('dst1 - Flip Vertically', dst1)

#左右翻轉
dst2 = cv2.flip(src, 1)
cv2.imshow('dst2 - Flip Horizontally', dst2)

# 左右+上下翻轉
dst3 = cv2.flip(src, -1)
cv2.imshow('dst3 - Horizontally and Vertically', dst3)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 影像仿射-影像平移
import cv2
import numpy as np

src = cv2.imread('rural.jpg')
cv2.imshow('Src', src)
height, width = src.shape[0:2]
dsize = (width, height)
x = 50
y = 100
M = np.array([[1, 0, x],
              [0, 1, y]],
              dtype=np.float32) # M矩陣的dtype必須是浮點數
dst = cv2.warpAffine(src, M, dsize)
cv2.imshow('Dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 影像仿射-影像旋轉
import cv2

src = cv2.imread('rural.jpg')
cv2.imshow('Src', src)
height, width = src.shape[0:2]
dsize = (width, height)

# 逆時針轉 30 度
M = cv2.getRotationMatrix2D((width/2, height/2), 30, 1)
dst1 = cv2.warpAffine(src, M, dsize)
cv2.imshow('Dst - counterclockwize', dst1)

# 順時針轉 30 度
M2 = cv2.getRotationMatrix2D((width/2, height/2), -30, 1)
dst2 = cv2.warpAffine(src, M2, dsize)
cv2.imshow('Dst - clockwize', dst2)

# 順時針 30 度+逆時針 15 度
M3 = cv2.getRotationMatrix2D((width/2, height/2), 15, 1)
dst3 = cv2.warpAffine(dst2, M3, dsize)
cv2.imshow('Dst - clockwize+counterclockwize', dst3)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 影像仿射-影像傾斜
import cv2
import numpy as np

src = cv2.imread('rural.jpg')
cv2.imshow('Src', src)
height, width = src.shape[0:2]
dsize = (width, height)

srcp = np.float32([[0, 0], [width-1, 0], [0, height-1]])
dstp = np.float32([[30, 0], [width-1, 0], [0, height-1]])
M = cv2.getAffineTransform(srcp, dstp)
dsize = (width, height)
dst = cv2.warpAffine(src, M, dsize)
cv2.imshow('Dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
# 影像仿射-影像透視
import cv2
import numpy as np

src = cv2.imread('tunnel.jpg')
cv2.imshow('Src', src)
height, width = src.shape[0:2]
a1 = [0, 0]
b1 = [width-1, 0]
c1 = [width-1, height-1]
d1 = [0, height-1]
srcp = np.float32([a1, b1, c1, d1])
a2 = [150, 0]
b2 = [width-150, 0]
c2 = [width-1, height-1]
d2 = [0, height-1]
dstp = np.float32([a2, b2, c2, d2])
M = cv2.getPerspectiveTransform(srcp, dstp)
dsize = (width, height)
dst = cv2.warpPerspective(src, M, dsize)
cv2.imshow('Dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
# 影像仿射-重映射1
import cv2
import numpy as np

src = np.random.randint(0, 256, size=[3, 4], dtype=np.uint8)
mapx = np.random.randint(0, src.shape[1], src.shape).astype(np.float32)
mapy = np.random.randint(0, src.shape[0], src.shape).astype(np.float32)
dst = cv2.remap(src, mapx, mapy, cv2.INTER_LINEAR)
print(f'src = \n{src}')
print(f'mapx = \n{mapx}')
print(f'mapy = \n{mapy}')
print(f'dst = \n{dst}')


src = 
[[211  52 100 113]
 [115 157 187  29]
 [201  80  40  99]]
mapx = 
[[0. 0. 2. 1.]
 [1. 2. 0. 3.]
 [0. 3. 0. 0.]]
mapy = 
[[2. 2. 1. 0.]
 [0. 2. 2. 2.]
 [2. 0. 2. 1.]]
dst = 
[[201 201 187  52]
 [ 52  40 201  99]
 [201 113 201 115]]


In [ ]:
# 影像仿射-重映射2
import cv2
import numpy as np

src = cv2.imread('tunnel.jpg')
rows, cols = src.shape[:2]
mapx = np.zeros(src.shape[:2], np.float32)
mapy = np.zeros(src.shape[:2], np.float32)
for r in range(rows):
    for c in range(cols):
        mapx[r, c] = c
        mapy[r, c] = 2*r
dst = cv2.remap(src, mapx, mapy, cv2.INTER_LINEAR)
print(mapy)
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
