In [ ]:
# erode()侵蝕
import cv2
import numpy as np

src = np.zeros((7, 7), np.uint8)
src[1:6, 1:6] = 1                   # 建立前景影像
kernel = np.ones((3, 3), np.uint8)  # 建立kernel
dst = cv2.erode(src, kernel)        # 侵蝕運算
print(f"src = \n {src}")
print(f"kernel = \n {kernel}")
print(f"Erosion = \n {dst}")

src = 
 [[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
kernel = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Erosion = 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
# erode()侵蝕
import cv2
import numpy as np

src = cv2.imread("bw.jpg")
kerne1 = np.ones((5, 5), np.uint8)
dst1 = cv2.erode(src, kerne1)
kerne2 = np.ones((11, 11), np.uint8)  
dst2 = cv2.erode(src, kerne2)        
cv2.imshow("src", src)
cv2.imshow("after erosion 5 x 5", dst1)
cv2.imshow("after erosion 11 x 11", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# erode()侵蝕
import cv2
import numpy as np

src = cv2.imread("bw_noise.jpg")
kerne1 = np.ones((3, 3), np.uint8)
dst1 = cv2.erode(src, kerne1)
kerne2 = np.ones((5, 5), np.uint8)  
dst2 = cv2.erode(src, kerne2)        
cv2.imshow("src", src)
cv2.imshow("after erosion 3 x 3", dst1)
cv2.imshow("after erosion 5 x 5", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# erode()侵蝕
import cv2
import numpy as np

src = cv2.imread("whilster.jpg")
kerne1 = np.ones((3, 3), np.uint8)
dst1 = cv2.erode(src, kerne1)
kerne2 = np.ones((5, 5), np.uint8)  
dst2 = cv2.erode(src, kerne2)        
cv2.imshow("src", src)
cv2.imshow("after erosion 3 x 3", dst1)
cv2.imshow("after erosion 5 x 5", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# dilate() 擴展
import cv2
import numpy as np

src = np.zeros((7, 7), np.uint8)
src[2:5, 2:5] = 1                   # 建立前景影像
kernel = np.ones((3, 3), np.uint8)  # 建立kernel
dst = cv2.dilate(src, kernel)       # 擴展運算
print(f"src = \n {src}")
print(f"kernel = \n {kernel}")
print(f"Dilation = \n {dst}")

src = 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
kernel = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Dilation = 
 [[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [4]:
# dilate()擴展
import cv2
import numpy as np

src = cv2.imread("bw_dilate.jpg")
kerne1 = np.ones((5, 5), np.uint8)
dst1 = cv2.dilate(src, kerne1)
kerne2 = np.ones((11, 11), np.uint8)  
dst2 = cv2.dilate(src, kerne2)        
cv2.imshow("src", src)
cv2.imshow("after dilation 5 x 5", dst1)
cv2.imshow("after dilation 11 x 11", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# dilate()擴展
import cv2
import numpy as np

src = cv2.imread("a.jpg")
kerne1 = np.ones((3, 3), np.uint8)
dst1 = cv2.dilate(src, kerne1)
kerne2 = np.ones((5, 5), np.uint8)  
dst2 = cv2.dilate(src, kerne2)        
cv2.imshow("src", src)
cv2.imshow("after dilation 3 x 3", dst1)
cv2.imshow("after dilation 5 x 5", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# dilate()擴展
import cv2
import numpy as np

src = cv2.imread("whilster.jpg")
kerne1 = np.ones((3, 3), np.uint8)
dst1 = cv2.dilate(src, kerne1)
kerne2 = np.ones((5, 5), np.uint8)  
dst2 = cv2.dilate(src, kerne2)        
cv2.imshow("src", src)
cv2.imshow("after dilation 3 x 3", dst1)
cv2.imshow("after dilation 5 x 5", dst2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# morphologyEx()開運算, 對影像先做侵蝕再做擴展
import cv2
import numpy as np

src = cv2.imread("btree.jpg")
kernel = np.ones((3, 3), np.uint8)
dst = cv2.morphologyEx(src, cv2.MORPH_OPEN, kernel)
cv2.imshow("src", src)
cv2.imshow("after Opening 3 x 3", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
# morphologyEx()開運算, 對影像先做侵蝕再做擴展
import cv2
import numpy as np

src = cv2.imread("night.png")
kernel = np.ones((9, 9), np.uint8)
mid = cv2.erode(src, kernel)
dst = cv2.dilate(mid, kernel)
cv2.imshow("src", src)
cv2.imshow("after erosion 9 x 9", mid)
cv2.imshow("after dilation 9 x 9", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
